/**
 * 영수증 HTML 생성 (터미널 .tsx에서 template literal 파서 혼동 방지)
 */

export function buildReceiptDocumentHtml(params: {
  title: string
  bodyContent: string
}): string {
  const { title, bodyContent } = params
  const c = (tag: string) => '\u003c/' + tag + '>'
  const styles = '@page { size: 80mm 200mm; margin: 0; } html, body { margin: 0; padding: 0; } body { width: 80mm; box-sizing: border-box; font-family: \'Noto Sans KR\', \'Malgun Gothic\', Arial, sans-serif; font-size: 12px; font-weight: 600; line-height: 1.42; letter-spacing: 0; padding-top: 0; padding-right: 0.2mm; padding-bottom: 1mm; padding-left: 0; color: #000; } .receipt-content { width: 73.2mm; max-width: 73.2mm; margin-left: 0; margin-right: auto; box-sizing: border-box; padding: 0 0.8mm 0 0; } .receipt-order-header .receipt-store-name { font-weight: 700; font-size: 13px; } .receipt-order-label { font-size: 11px; color: #333; margin-top: 2px; } .receipt-section-title { text-align: center; font-size: 12px; font-weight: 700; letter-spacing: 0.08em; margin-bottom: 2px; } .receipt-sub-title { text-align: center; font-size: 11px; color: #000; } .receipt-divider { border-top: 1px dashed #000; margin: 8px 0; } .receipt-divider-strong { border-top: 2px solid #111; margin: 8px 0; } .receipt-row { display: grid; grid-template-columns: minmax(0, 1fr) auto; column-gap: 7px; align-items: start; margin: 4px 0; padding-right: 1.2mm; } .receipt-row > span:first-child { min-width: 0; overflow-wrap: anywhere; word-break: break-word; } .receipt-row > span:last-child { white-space: normal; text-align: right; overflow-wrap: anywhere; word-break: break-word; } .receipt-meta-row { display: grid; grid-template-columns: 11mm minmax(0, 1fr); column-gap: 4px; align-items: start; margin: 3px 0; padding-right: 1.2mm; } .receipt-meta-label { white-space: nowrap; } .receipt-meta-value { min-width: 0; text-align: left; overflow-wrap: anywhere; word-break: break-word; } .receipt-item-head { display: grid; grid-template-columns: minmax(0, 1fr) auto; column-gap: 7px; font-size: 11px; font-weight: 700; padding: 0 1.2mm 4px 0; border-bottom: 1px solid #cbd5e1; } .biz-line { margin: 2px 0; font-size: 11px; } .biz-strong { color: #111; font-weight: 600; } .receipt-total { margin-top: 8px; padding-top: 4px; font-weight: bold; } .discount { color: #166534; } .memo { margin-top: 6px; font-size: 11px; color: #000; } .receipt-muted { color: #000; } .paid-stamp-wrap { text-align: center; margin: 10px 0; } .paid-stamp { display: inline-block; border: 1px solid #111; padding: 2px 12px; font-size: 11px; font-weight: 700; letter-spacing: 0.12em; } .footer-strong { color: #111; font-weight: 600; } .text-center { text-align: center; } .text-xs { font-size: 11px; }'
  return '<!DOCTYPE html><html><head><title>' + title + '</title><style>' + styles + '</style>' + c('head') + '<body>' + bodyContent + c('body') + c('html')
}
