-- 근태 조정 이력(원본 보존) 테이블
-- 목적: late/early/ot 조정 시 before/after를 저장해 UI에서 "전→후" 표시 및 감사 추적

create table if not exists public.attendance_log_adjustments (
  id bigint generated by default as identity primary key,
  attendance_log_id bigint not null,
  log_type text not null,
  metric text not null check (metric in ('late_min', 'early_min', 'ot_min')),
  before_value integer not null check (before_value >= 0),
  after_value integer not null check (after_value >= 0),
  reason text null,
  changed_by_role text null,
  changed_by_store text null,
  source text null default 'processAttendanceApproval',
  changed_at timestamptz not null default now()
);

create index if not exists idx_attendance_log_adjustments_log_metric_time
  on public.attendance_log_adjustments (attendance_log_id, metric, changed_at asc, id asc);

comment on table public.attendance_log_adjustments is '근태 조정 이력(before/after) 보존';
