-- CRM 쿠폰 캠페인 통합 (POS + 회원포털 + CRM)
-- 실행 대상: Supabase SQL Editor (PostgreSQL)

-- 0) 선행 테이블 가드 (신규/부분 환경에서도 본 SQL 1회 실행 가능)
do $$
begin
  if to_regclass('public.members') is not null then
    create table if not exists public.member_coupon_issues (
      id bigint generated by default as identity primary key,
      member_id bigint references public.members(id) on delete cascade,
      coupon_code text not null,
      issued_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
      used_at timestamp without time zone,
      order_id bigint,
      status text not null default 'issued'
    );
    create index if not exists idx_member_coupon_issues_member_id
      on public.member_coupon_issues(member_id);
  else
    raise notice 'skip: public.members not found — member_coupon_issues not created';
  end if;
end $$;

do $$
begin
  if to_regclass('public.pos_orders') is not null
     and to_regclass('public.pos_coupons') is not null then
    create table if not exists public.pos_order_coupon_redemptions (
      id bigserial primary key,
      order_id bigint not null references public.pos_orders(id) on delete cascade,
      store_code text not null,
      coupon_id bigint references public.pos_coupons(id),
      coupon_code text not null,
      discount_amt numeric(14,2) not null default 0,
      quantity integer not null default 1,
      serial_id bigint,
      member_coupon_issue_id bigint,
      created_at timestamptz not null default now()
    );
    create index if not exists idx_pos_order_coupon_redemptions_order_id
      on public.pos_order_coupon_redemptions(order_id);
  else
    raise notice 'skip: pos_orders/pos_coupons not found — pos_order_coupon_redemptions not created';
  end if;
end $$;

-- 1) 캠페인 마스터
create table if not exists public.crm_coupon_campaigns (
  id bigint generated by default as identity primary key,
  campaign_key text unique,
  name text not null,
  description text,
  status text not null default 'draft', -- draft/active/paused/archived
  trigger_type text not null default 'manual', -- manual/auto
  audience_type text not null default 'all', -- all/tier/recent/dormant/birthday_month/new_joined
  audience_payload jsonb not null default '{}'::jsonb,
  coupon_code text not null,
  issue_limit integer,
  starts_at timestamp without time zone,
  ends_at timestamp without time zone,
  auto_schedule jsonb not null default '{}'::jsonb,
  created_by text,
  updated_by text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_crm_coupon_campaigns_status
  on public.crm_coupon_campaigns(status, updated_at desc);

create index if not exists idx_crm_coupon_campaigns_coupon_code
  on public.crm_coupon_campaigns(coupon_code);

comment on column public.crm_coupon_campaigns.auto_schedule
  is 'auto 실행 스케줄 (Bangkok 기준) 예: {"timezone":"Asia/Bangkok","at":"10:00","days":["mon","wed"]}';

-- POS 쿠폰 엔진 고도화 컬럼 (1+1/세트/상품지정/우선순위)
do $$
begin
  if to_regclass('public.pos_coupons') is not null then
    alter table public.pos_coupons
      add column if not exists benefit_kind text, -- bogo/set_fixed/item_fixed/null
      add column if not exists set_qty integer,
      add column if not exists item_scope_json jsonb,
      add column if not exists priority integer not null default 0,
      add column if not exists combinable_with_manual_discount boolean not null default true;
  else
    raise notice 'skip: public.pos_coupons not found';
  end if;
end $$;

-- 2) 캠페인 실행 이력
create table if not exists public.crm_coupon_campaign_runs (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.crm_coupon_campaigns(id) on delete cascade,
  run_mode text not null default 'manual', -- manual/auto/retry
  run_reason text,
  target_count integer not null default 0,
  issued_count integer not null default 0,
  skipped_count integer not null default 0,
  failed_count integer not null default 0,
  executed_by text,
  executed_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_crm_coupon_campaign_runs_campaign_id
  on public.crm_coupon_campaign_runs(campaign_id, executed_at desc);

-- 3) 실행 대상 멤버 상세 이력 (재실행/디버깅용)
do $$
begin
  if to_regclass('public.members') is not null
     and to_regclass('public.member_coupon_issues') is not null then
    create table if not exists public.crm_coupon_campaign_run_members (
      id bigint generated by default as identity primary key,
      run_id bigint not null references public.crm_coupon_campaign_runs(id) on delete cascade,
      campaign_id bigint not null references public.crm_coupon_campaigns(id) on delete cascade,
      member_id bigint not null references public.members(id) on delete cascade,
      status text not null default 'issued', -- issued/skipped/failed
      reason text,
      member_coupon_issue_id bigint references public.member_coupon_issues(id) on delete set null,
      created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
      unique (run_id, member_id)
    );
    create index if not exists idx_crm_coupon_campaign_run_members_campaign
      on public.crm_coupon_campaign_run_members(campaign_id, created_at desc);
    create index if not exists idx_crm_coupon_campaign_run_members_member
      on public.crm_coupon_campaign_run_members(member_id, created_at desc);
  else
    raise notice 'skip: members/member_coupon_issues not found — crm_coupon_campaign_run_members not created';
  end if;
end $$;

-- 4) 회원 쿠폰 이슈 확장 (캠페인/만료/복원 추적)
do $$
begin
  if to_regclass('public.member_coupon_issues') is not null then
    alter table public.member_coupon_issues
      add column if not exists campaign_id bigint references public.crm_coupon_campaigns(id) on delete set null,
      add column if not exists expires_at timestamp without time zone,
      add column if not exists issued_store_scope jsonb,
      add column if not exists restored_at timestamp without time zone,
      add column if not exists restore_reason text,
      add column if not exists restored_from_order_id bigint;

    create index if not exists idx_member_coupon_issues_member_status_expires
      on public.member_coupon_issues(member_id, status, expires_at);

    create index if not exists idx_member_coupon_issues_campaign
      on public.member_coupon_issues(campaign_id, issued_at desc);

    create index if not exists idx_member_coupon_issues_restored_order
      on public.member_coupon_issues(restored_from_order_id);

    comment on column public.member_coupon_issues.status
      is 'issued/used/expired/cancelled/restored';

    create unique index if not exists uq_member_coupon_issues_campaign_member_code_issued
      on public.member_coupon_issues(member_id, coupon_code, coalesce(campaign_id, 0))
      where status = 'issued';
  else
    raise notice 'skip: member_coupon_issues not found — column/index extension skipped';
  end if;
end $$;

-- 5) POS 쿠폰 사용 멱등성 강화 (주문+회원쿠폰 기준)
do $$
begin
  if to_regclass('public.pos_order_coupon_redemptions') is not null then
    create unique index if not exists uq_pos_order_coupon_redemptions_order_member_issue
      on public.pos_order_coupon_redemptions(order_id, member_coupon_issue_id)
      where member_coupon_issue_id is not null;
  end if;
end $$;

