-- RPKM2026: POS 쿠폰은 있는데 시크릿 프로모 코드가 없어 앱에서 invalid_code 발생
-- 회원앱 「มีรหัสคูปองพิเศษ?」 → member_coupon_promo_codes 조회
-- Supabase SQL Editor에서 실행

-- 0) 테이블 없으면 생성 (이미 있으면 스킵)
--    전체 DDL: sql/member_coupon_promo_codes.sql

create table if not exists public.member_coupon_promo_codes (
  id bigint generated by default as identity primary key,
  code text not null,
  coupon_code text not null,
  label text not null default '',
  note text not null default '',
  is_active boolean not null default true,
  valid_from date,
  valid_to date,
  max_redemptions integer,
  max_per_member integer not null default 1,
  redemption_count integer not null default 0,
  tenant_id text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  constraint member_coupon_promo_codes_max_per_member_chk check (max_per_member >= 1),
  constraint member_coupon_promo_codes_max_redemptions_chk
    check (max_redemptions is null or max_redemptions >= 1),
  constraint member_coupon_promo_codes_redemption_count_chk check (redemption_count >= 0)
);

create unique index if not exists idx_member_coupon_promo_codes_tenant_code
  on public.member_coupon_promo_codes ((coalesce(tenant_id, '')), code);

-- 1) 시크릿 코드 RPKM2026 → 지갑 쿠폰 RPKM2026 연결
INSERT INTO public.member_coupon_promo_codes (
  code,
  coupon_code,
  label,
  note,
  is_active,
  valid_from,
  valid_to,
  max_redemptions,
  max_per_member,
  redemption_count
)
SELECT
  'RPKM2026',
  'RPKM2026',
  coalesce(nullif(btrim(c.name), ''), 'RPKM2026'),
  'Chulalongkorn student cash coupon 200 THB',
  true,
  coalesce(c.valid_from, date '2026-07-23'),
  coalesce(c.valid_to, date '2026-10-31'),
  null,
  1,
  0
FROM public.pos_coupons c
WHERE upper(trim(c.code)) = 'RPKM2026'
  AND NOT EXISTS (
    SELECT 1
    FROM public.member_coupon_promo_codes p
    WHERE upper(trim(p.code)) = 'RPKM2026'
      AND coalesce(p.tenant_id, '') = ''
  );

-- 2) 이미 있으면 활성·기간만 맞춤
UPDATE public.member_coupon_promo_codes AS p
SET
  coupon_code = 'RPKM2026',
  is_active = true,
  valid_from = coalesce(c.valid_from, p.valid_from, date '2026-07-23'),
  valid_to = coalesce(c.valid_to, p.valid_to, date '2026-10-31'),
  label = coalesce(nullif(btrim(p.label), ''), nullif(btrim(c.name), ''), 'RPKM2026'),
  updated_at = (now() at time zone 'Asia/Bangkok')
FROM public.pos_coupons AS c
WHERE upper(trim(p.code)) = 'RPKM2026'
  AND upper(trim(c.code)) = 'RPKM2026';

-- 3) 확인
SELECT id, code, coupon_code, label, is_active, valid_from, valid_to,
       max_per_member, redemption_count
FROM public.member_coupon_promo_codes
WHERE upper(trim(code)) = 'RPKM2026';

SELECT code, name, redemption_mode, is_active, valid_from, valid_to
FROM public.pos_coupons
WHERE upper(trim(code)) = 'RPKM2026';

-- 4) 이후 앱에서 RPKM2026 다시 입력 → คูปองของฉัน 에 200บาท 쿠폰 수령
