-- 인테리어 관리 고도화 (공정/업체/배치/자재)
-- 기존 interior_* 테이블과 독립적으로 추가되며 project_id 기준으로 조회한다.

CREATE TABLE IF NOT EXISTS interior_work_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  part_type text NOT NULL DEFAULT '',
  title text NOT NULL DEFAULT '',
  description text,
  start_date date,
  end_date date,
  status text NOT NULL DEFAULT 'planned',
  progress_pct numeric(5,2) NOT NULL DEFAULT 0,
  color text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_interior_work_packages_project
  ON interior_work_packages (project_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_interior_work_packages_dates
  ON interior_work_packages (project_id, start_date, end_date);

ALTER TABLE interior_work_packages
  DROP CONSTRAINT IF EXISTS chk_interior_work_packages_status;
ALTER TABLE interior_work_packages
  ADD CONSTRAINT chk_interior_work_packages_status
  CHECK (status IN ('planned', 'in_progress', 'blocked', 'done', 'cancelled'));

ALTER TABLE interior_work_packages
  DROP CONSTRAINT IF EXISTS chk_interior_work_packages_progress_pct;
ALTER TABLE interior_work_packages
  ADD CONSTRAINT chk_interior_work_packages_progress_pct
  CHECK (progress_pct >= 0 AND progress_pct <= 100);

CREATE TABLE IF NOT EXISTS interior_vendor_tracks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  vendor_name text NOT NULL DEFAULT '',
  vendor_code text,
  work_package_id bigint REFERENCES interior_work_packages(id) ON DELETE SET NULL,
  payment_due_date date,
  payment_paid_date date,
  material_eta_date date,
  material_received_date date,
  work_completed_date date,
  status text NOT NULL DEFAULT 'planned',
  amount numeric(14,2) NOT NULL DEFAULT 0,
  note text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_interior_vendor_tracks_project
  ON interior_vendor_tracks (project_id, sort_order, id);
CREATE INDEX IF NOT EXISTS idx_interior_vendor_tracks_work_package
  ON interior_vendor_tracks (work_package_id);

ALTER TABLE interior_vendor_tracks
  DROP CONSTRAINT IF EXISTS chk_interior_vendor_tracks_status;
ALTER TABLE interior_vendor_tracks
  ADD CONSTRAINT chk_interior_vendor_tracks_status
  CHECK (status IN ('planned', 'ordered', 'paid', 'received', 'done', 'delayed', 'cancelled'));

CREATE TABLE IF NOT EXISTS interior_layout_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  zone text NOT NULL DEFAULT 'hall',
  floor text,
  x numeric(10,2) NOT NULL DEFAULT 0,
  y numeric(10,2) NOT NULL DEFAULT 0,
  w numeric(10,2) NOT NULL DEFAULT 1,
  h numeric(10,2) NOT NULL DEFAULT 1,
  rotation numeric(6,2) NOT NULL DEFAULT 0,
  item_name text NOT NULL DEFAULT '',
  qty numeric(10,2) NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'planned',
  material_spec_id bigint,
  note text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_interior_layout_items_project
  ON interior_layout_items (project_id, zone, sort_order, id);

ALTER TABLE interior_layout_items
  DROP CONSTRAINT IF EXISTS chk_interior_layout_items_zone;
ALTER TABLE interior_layout_items
  ADD CONSTRAINT chk_interior_layout_items_zone
  CHECK (zone IN ('kitchen', 'hall'));

ALTER TABLE interior_layout_items
  DROP CONSTRAINT IF EXISTS chk_interior_layout_items_status;
ALTER TABLE interior_layout_items
  ADD CONSTRAINT chk_interior_layout_items_status
  CHECK (status IN ('planned', 'ordered', 'installed', 'done', 'blocked'));

CREATE TABLE IF NOT EXISTS interior_material_specs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  material_code text,
  material_name text NOT NULL DEFAULT '',
  spec text,
  supplier text,
  unit text,
  unit_cost numeric(14,2) NOT NULL DEFAULT 0,
  image_url text,
  location text,
  note text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_interior_material_specs_project
  ON interior_material_specs (project_id, sort_order, id);

ALTER TABLE interior_layout_items
  DROP CONSTRAINT IF EXISTS fk_interior_layout_items_material_spec_id;
ALTER TABLE interior_layout_items
  ADD CONSTRAINT fk_interior_layout_items_material_spec_id
  FOREIGN KEY (material_spec_id) REFERENCES interior_material_specs(id) ON DELETE SET NULL;

-- 레이아웃 편집 사용자 기본값(복제 오프셋 등) - 프로젝트/존/사용자 단위
CREATE TABLE IF NOT EXISTS interior_layout_editor_prefs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL,
  zone text NOT NULL DEFAULT 'kitchen',
  user_key text NOT NULL,
  user_store text,
  user_name text,
  employee_id bigint,
  duplicate_offset_x numeric(10,2) NOT NULL DEFAULT 0.5,
  duplicate_offset_y numeric(10,2) NOT NULL DEFAULT 0.5,
  snap_enabled boolean NOT NULL DEFAULT true,
  snap_step numeric(10,2) NOT NULL DEFAULT 0.5,
  nudge_small numeric(10,2) NOT NULL DEFAULT 0.1,
  nudge_medium numeric(10,2) NOT NULL DEFAULT 0.5,
  nudge_large numeric(10,2) NOT NULL DEFAULT 1.0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE interior_layout_editor_prefs
  ADD COLUMN IF NOT EXISTS duplicate_offset_x numeric(10,2) NOT NULL DEFAULT 0.5;
ALTER TABLE interior_layout_editor_prefs
  ADD COLUMN IF NOT EXISTS duplicate_offset_y numeric(10,2) NOT NULL DEFAULT 0.5;
ALTER TABLE interior_layout_editor_prefs
  ADD COLUMN IF NOT EXISTS snap_enabled boolean NOT NULL DEFAULT true;
ALTER TABLE interior_layout_editor_prefs
  ADD COLUMN IF NOT EXISTS snap_step numeric(10,2) NOT NULL DEFAULT 0.5;
ALTER TABLE interior_layout_editor_prefs
  ADD COLUMN IF NOT EXISTS nudge_small numeric(10,2) NOT NULL DEFAULT 0.1;
ALTER TABLE interior_layout_editor_prefs
  ADD COLUMN IF NOT EXISTS nudge_medium numeric(10,2) NOT NULL DEFAULT 0.5;
ALTER TABLE interior_layout_editor_prefs
  ADD COLUMN IF NOT EXISTS nudge_large numeric(10,2) NOT NULL DEFAULT 1.0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_interior_layout_editor_prefs_scope
  ON interior_layout_editor_prefs (project_id, zone, user_key);

CREATE INDEX IF NOT EXISTS idx_interior_layout_editor_prefs_lookup
  ON interior_layout_editor_prefs (project_id, zone, user_store, user_name);

ALTER TABLE interior_layout_editor_prefs
  DROP CONSTRAINT IF EXISTS chk_interior_layout_editor_prefs_zone;
ALTER TABLE interior_layout_editor_prefs
  ADD CONSTRAINT chk_interior_layout_editor_prefs_zone
  CHECK (zone IN ('kitchen', 'hall'));
