-- 인테리어 업체 마스터 (전 프로젝트 공통)
-- Supabase SQL Editor에서 실행. 프로젝트별 추적은 interior_vendor_tracks 유지.

CREATE TABLE IF NOT EXISTS interior_vendor_directory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text,
  name text NOT NULL DEFAULT '',
  contact_name text,
  phone text,
  email text,
  address text,
  specialty text,
  memo text,
  use_count integer NOT NULL DEFAULT 0,
  last_used_at timestamptz,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_interior_vendor_directory_name_norm
  ON interior_vendor_directory (lower(trim(name)));

CREATE UNIQUE INDEX IF NOT EXISTS idx_interior_vendor_directory_code_norm
  ON interior_vendor_directory (lower(trim(code)))
  WHERE code IS NOT NULL AND trim(code) <> '';

CREATE INDEX IF NOT EXISTS idx_interior_vendor_directory_active_sort
  ON interior_vendor_directory (is_active DESC, sort_order ASC, name ASC);

-- 기존 프로젝트 추적에 쓰인 업체명 → 마스터 초기 적재
INSERT INTO interior_vendor_directory (name, use_count, last_used_at)
SELECT s.vendor_name, s.cnt, s.last_at
FROM (
  SELECT
    trim(vendor_name) AS vendor_name,
    count(*)::integer AS cnt,
    max(coalesce(updated_at, created_at)) AS last_at
  FROM interior_vendor_tracks
  WHERE trim(vendor_name) <> ''
  GROUP BY lower(trim(vendor_name)), trim(vendor_name)
) s
WHERE NOT EXISTS (
  SELECT 1
  FROM interior_vendor_directory d
  WHERE lower(trim(d.name)) = lower(trim(s.vendor_name))
);

-- 업체·계약 저장 시 마스터 자동 반영 (코드 우선, 없으면 이름)
CREATE OR REPLACE FUNCTION public.upsert_interior_vendor_directory(
  p_name text,
  p_code text DEFAULT NULL,
  p_contact_name text DEFAULT NULL,
  p_phone text DEFAULT NULL,
  p_email text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id bigint;
  v_name text := trim(coalesce(p_name, ''));
  v_code text := nullif(trim(coalesce(p_code, '')), '');
BEGIN
  IF v_name = '' THEN
    RETURN NULL;
  END IF;

  IF v_code IS NOT NULL THEN
    SELECT id INTO v_id
    FROM interior_vendor_directory
    WHERE lower(trim(code)) = lower(v_code)
    LIMIT 1;
  END IF;

  IF v_id IS NULL THEN
    SELECT id INTO v_id
    FROM interior_vendor_directory
    WHERE lower(trim(name)) = lower(v_name)
    LIMIT 1;
  END IF;

  IF v_id IS NOT NULL THEN
    UPDATE interior_vendor_directory
    SET
      use_count = use_count + 1,
      last_used_at = now(),
      updated_at = now(),
      code = COALESCE(v_code, code),
      contact_name = COALESCE(nullif(trim(coalesce(p_contact_name, '')), ''), contact_name),
      phone = COALESCE(nullif(trim(coalesce(p_phone, '')), ''), phone),
      email = COALESCE(nullif(trim(coalesce(p_email, '')), ''), email)
    WHERE id = v_id;
    RETURN v_id;
  END IF;

  INSERT INTO interior_vendor_directory (
    name, code, contact_name, phone, email, use_count, last_used_at
  )
  VALUES (
    v_name,
    v_code,
    nullif(trim(coalesce(p_contact_name, '')), ''),
    nullif(trim(coalesce(p_phone, '')), ''),
    nullif(trim(coalesce(p_email, '')), ''),
    1,
    now()
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

ALTER TABLE IF EXISTS public.interior_vendor_directory ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all interior_vendor_directory" ON public.interior_vendor_directory;
CREATE POLICY "Allow all interior_vendor_directory"
  ON public.interior_vendor_directory
  FOR ALL
  USING (true)
  WITH CHECK (true);
