-- 인플루언서 명부(인물 마스터) — 캠페인과 무관하게 섭외·레이트·상태를 관리
-- 1/4: 테이블 생성. Supabase SQL Editor에서 이 파일만 Run → 이후 02, 03, 04 순서

CREATE TABLE IF NOT EXISTS public.marketing_influencer_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id text,
  display_name text NOT NULL DEFAULT '',
  content_categories text[] NOT NULL DEFAULT '{}',
  tiktok_url text NOT NULL DEFAULT '',
  tiktok_handle text NOT NULL DEFAULT '',
  tiktok_followers bigint,
  instagram_url text NOT NULL DEFAULT '',
  instagram_handle text NOT NULL DEFAULT '',
  instagram_followers bigint,
  facebook_url text NOT NULL DEFAULT '',
  facebook_followers bigint,
  contact text NOT NULL DEFAULT '',
  contact_name text NOT NULL DEFAULT '',
  contact_phone text NOT NULL DEFAULT '',
  rate_tiktok text NOT NULL DEFAULT '',
  rate_instagram text NOT NULL DEFAULT '',
  rate_facebook text NOT NULL DEFAULT '',
  rate_package text NOT NULL DEFAULT '',
  rate_min_thb numeric,
  rate_includes text NOT NULL DEFAULT '',
  extra_cost text NOT NULL DEFAULT '',
  preferred_store text NOT NULL DEFAULT '',
  rate_inquired_at date,
  pipeline_status text NOT NULL DEFAULT 'waiting',
  rate_card_url text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  created_by text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_marketing_influencer_profiles_tenant_id
  ON public.marketing_influencer_profiles (tenant_id);

CREATE INDEX IF NOT EXISTS idx_marketing_influencer_profiles_status
  ON public.marketing_influencer_profiles (pipeline_status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_marketing_influencer_profiles_tiktok
  ON public.marketing_influencer_profiles (coalesce(tenant_id, ''), lower(tiktok_handle))
  WHERE tiktok_handle <> '';

COMMENT ON TABLE public.marketing_influencer_profiles IS '인플루언서 명부(인물 1명 = 1행). 업로드 기록은 marketing_influencers.profile_id 로 연결';
COMMENT ON COLUMN public.marketing_influencer_profiles.pipeline_status IS 'waiting|interested|got_rate|high_rate|hired|not_selected|no_reply|unavailable';
COMMENT ON COLUMN public.marketing_influencer_profiles.rate_min_thb IS '레이트 원문에서 파싱한 최저 금액(THB), 파싱 불가 시 NULL';
COMMENT ON COLUMN public.marketing_influencer_profiles.preferred_store IS '시트 พื้นที่รับงาน — ERP 매장명으로 매핑, 실패 시 원문';
