-- 회원 등급: LINE OA 기준 포인트·누적금액 + 회원앱 혜택 문구
-- Supabase SQL Editor에서 한 번에 실행 (테이블 없어도 동작)

-- 1) members 로열티 컬럼 (없으면 추가)
alter table public.members
  add column if not exists tier_code text default 'BRONZE',
  add column if not exists lifetime_amount numeric(14,2) not null default 0,
  add column if not exists point_balance integer not null default 0;

-- 2) 등급 마스터 테이블 (없으면 생성)
create table if not exists public.member_tiers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  min_amount numeric(14,2) not null default 0,
  min_points integer not null default 0,
  point_rate numeric(8,4) not null default 0.0100,
  sort_order integer not null default 0,
  benefits_ko text,
  benefits_en text,
  benefits_th text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

-- 3) 기존 테이블에 컬럼만 부족한 경우 보강
alter table public.member_tiers
  add column if not exists min_points integer not null default 0,
  add column if not exists sort_order integer not null default 0,
  add column if not exists benefits_ko text,
  add column if not exists benefits_en text,
  add column if not exists benefits_th text;

-- 4) 등급 변경 이력 (선택·없으면 생성 — POS 등급 재계산용)
create table if not exists public.member_tier_histories (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  prev_tier_code text,
  next_tier_code text not null,
  reason text,
  changed_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_tier_histories_member_id on public.member_tier_histories(member_id);

-- 5) VIP → DIAMOND (LINE OA 명칭 통일)
update public.members set tier_code = 'DIAMOND' where tier_code = 'VIP';

-- 6) LINE OA 기준 시드
insert into public.member_tiers (code, name, min_amount, min_points, point_rate, sort_order, benefits_ko, benefits_en, benefits_th)
values
  (
    'BRONZE',
    'Bronze',
    0,
    0,
    0.0100,
    1,
    '기본 회원 등급입니다.',
    'Basic membership level.',
    'สมาชิกระดับพื้นฐาน'
  ),
  (
    'SILVER',
    'Silver',
    3000,
    120,
    0.0125,
    2,
    null,
    null,
    null
  ),
  (
    'GOLD',
    'Gold',
    6000,
    240,
    0.0150,
    3,
    null,
    null,
    null
  ),
  (
    'DIAMOND',
    'Diamond',
    10000,
    400,
    0.0200,
    4,
    null,
    null,
    null
  )
on conflict (code) do update
set
  name = excluded.name,
  min_amount = excluded.min_amount,
  min_points = excluded.min_points,
  point_rate = excluded.point_rate,
  sort_order = excluded.sort_order,
  benefits_ko = coalesce(public.member_tiers.benefits_ko, excluded.benefits_ko),
  benefits_en = coalesce(public.member_tiers.benefits_en, excluded.benefits_en),
  benefits_th = coalesce(public.member_tiers.benefits_th, excluded.benefits_th),
  updated_at = (now() at time zone 'Asia/Bangkok');

delete from public.member_tiers where code = 'VIP';

-- 7) 승급 기준 설정 + tier_points (포인트 기준 승급용)
alter table public.members
  add column if not exists tier_points integer not null default 0;

insert into public.system_settings (key, value_json, updated_at)
values ('member_tier_upgrade_basis', '"points"'::jsonb, (now() at time zone 'Asia/Bangkok'))
on conflict (key) do nothing;

update public.members m
set tier_points = greatest(
  coalesce(m.tier_points, 0),
  coalesce(sub.sum_pts, 0),
  coalesce(m.line_tier_points, 0)
)
from (
  select
    member_id,
    coalesce(sum(case when points > 0 then points else 0 end), 0)::integer as sum_pts
  from public.member_points_ledger
  group by member_id
) sub
where m.id = sub.member_id;

update public.members
set tier_points = greatest(coalesce(tier_points, 0), coalesce(line_tier_points, 0))
where coalesce(line_tier_points, 0) > coalesce(tier_points, 0);
