-- 회원앱 시크릿 쿠폰 프로모 코드 (코드 입력 → member_issue 지갑 발급)
-- 실행 대상: Supabase SQL Editor (PostgreSQL)
-- POS reusable_code 와 별개 — 회원앱에서만 입력·수령

create table if not exists public.member_coupon_promo_codes (
  id bigint generated by default as identity primary key,
  code text not null,
  coupon_code text not null,
  label text not null default '',
  note text not null default '',
  is_active boolean not null default true,
  valid_from date,
  valid_to date,
  max_redemptions integer,
  max_per_member integer not null default 1,
  redemption_count integer not null default 0,
  tenant_id text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  constraint member_coupon_promo_codes_max_per_member_chk check (max_per_member >= 1),
  constraint member_coupon_promo_codes_max_redemptions_chk
    check (max_redemptions is null or max_redemptions >= 1),
  constraint member_coupon_promo_codes_redemption_count_chk check (redemption_count >= 0)
);

create unique index if not exists idx_member_coupon_promo_codes_tenant_code
  on public.member_coupon_promo_codes ((coalesce(tenant_id, '')), code);

create index if not exists idx_member_coupon_promo_codes_coupon_code
  on public.member_coupon_promo_codes (coupon_code);

create index if not exists idx_member_coupon_promo_codes_active
  on public.member_coupon_promo_codes (is_active, valid_from, valid_to);

comment on table public.member_coupon_promo_codes is
  'Member-app secret promo codes. Entering code issues linked member_issue coupon to wallet.';
comment on column public.member_coupon_promo_codes.code is
  'Secret code members type (stored uppercase). Not a POS reusable_code.';
comment on column public.member_coupon_promo_codes.coupon_code is
  'pos_coupons.code to issue (must be redemption_mode=member_issue).';
comment on column public.member_coupon_promo_codes.max_redemptions is
  'Global success cap; null = unlimited.';
comment on column public.member_coupon_promo_codes.max_per_member is
  'Max successful redemptions per member for this promo code.';
comment on column public.member_coupon_promo_codes.redemption_count is
  'Successful redemption counter (denormalized).';

do $$
begin
  if to_regclass('public.members') is not null then
    create table if not exists public.member_coupon_promo_redemptions (
      id bigint generated by default as identity primary key,
      promo_code_id bigint not null
        references public.member_coupon_promo_codes(id) on delete cascade,
      member_id bigint not null
        references public.members(id) on delete cascade,
      issue_id bigint,
      redeemed_at timestamp without time zone not null
        default (now() at time zone 'Asia/Bangkok'),
      tenant_id text
    );
    create index if not exists idx_member_coupon_promo_redemptions_promo_member
      on public.member_coupon_promo_redemptions (promo_code_id, member_id);
    create index if not exists idx_member_coupon_promo_redemptions_member
      on public.member_coupon_promo_redemptions (member_id, redeemed_at desc);
    comment on table public.member_coupon_promo_redemptions is
      'Audit log of successful secret promo code redemptions.';
  else
    raise notice 'skip: public.members not found — member_coupon_promo_redemptions not created';
  end if;
end $$;
