-- 멤버십 스탬프 카드 (방문 적립 · 마일스톤 쿠폰 자동 지급)
-- Supabase SQL Editor에서 실행

alter table public.members
  add column if not exists stamp_card_balance integer not null default 0,
  add column if not exists stamp_card_sequence integer not null default 1;

create table if not exists public.member_stamp_milestones (
  id bigint generated by default as identity primary key,
  stamp_count integer not null check (stamp_count > 0),
  coupon_code text not null,
  label_ko text,
  label_en text,
  label_th text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_stamp_milestones_active_sort
  on public.member_stamp_milestones(is_active, sort_order, stamp_count);

create table if not exists public.member_stamp_ledger (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  order_id bigint,
  store_code text,
  stamp_ymd text not null,
  card_sequence integer not null default 1,
  kind text not null default 'earn',
  balance_after integer not null default 0,
  note text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_stamp_ledger_member_id
  on public.member_stamp_ledger(member_id, created_at desc);

create unique index if not exists uq_member_stamp_ledger_order_earn
  on public.member_stamp_ledger(member_id, order_id)
  where order_id is not null and kind = 'earn';

create table if not exists public.member_stamp_reward_issues (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  milestone_id bigint not null references public.member_stamp_milestones(id) on delete cascade,
  card_sequence integer not null default 1,
  coupon_code text not null,
  coupon_issue_id bigint,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create unique index if not exists uq_member_stamp_reward_member_milestone_seq
  on public.member_stamp_reward_issues(member_id, milestone_id, card_sequence);
