-- 스탬프 카드 고도화 (마일스톤 포인트·실패 로그·카드 시작일·수동조정/회수 kind)
-- member_stamp_card.sql 적용 후 실행

alter table public.members
  add column if not exists stamp_card_started_at timestamp without time zone;

alter table public.member_stamp_milestones
  add column if not exists reward_type text not null default 'coupon',
  add column if not exists reward_points integer not null default 0;

alter table public.member_stamp_milestones
  alter column coupon_code drop not null;

create table if not exists public.member_stamp_issue_logs (
  id bigint generated by default as identity primary key,
  member_id bigint references public.members(id) on delete set null,
  milestone_id bigint references public.member_stamp_milestones(id) on delete set null,
  order_id bigint,
  coupon_code text,
  error_message text not null,
  context jsonb,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_stamp_issue_logs_created
  on public.member_stamp_issue_logs(created_at desc);

create index if not exists idx_member_stamp_issue_logs_member
  on public.member_stamp_issue_logs(member_id, created_at desc);
