-- 회원/CRM 30만 확장 공통 마이그레이션
-- 목적:
-- 1) 회원 필수 필드 확장(국적/가입경로/추천인)
-- 2) 회원 포털 OTP/세션 테이블
-- 3) 포인트 원장 멱등 인덱스
-- 4) CRM 요약/세그먼트/RFM RPC
-- 실행: Supabase SQL Editor

alter table public.members
  add column if not exists full_name text,
  add column if not exists birth_date text,
  add column if not exists gender text,
  add column if not exists tier_code text default 'BRONZE',
  add column if not exists point_balance integer not null default 0,
  add column if not exists lifetime_amount numeric(14,2) not null default 0,
  add column if not exists nationality text,
  add column if not exists join_channel text default 'store',
  add column if not exists referred_by_member_id bigint references public.members(id) on delete set null,
  add column if not exists referral_code text,
  add column if not exists last_visited_at timestamp without time zone;

create unique index if not exists uq_members_referral_code
  on public.members (referral_code)
  where referral_code is not null;

create index if not exists idx_members_join_channel on public.members(join_channel);
create index if not exists idx_members_last_visited_at on public.members(last_visited_at desc);
create index if not exists idx_members_referred_by on public.members(referred_by_member_id);

-- 전화번호 정규화 검색/중복 방지(값이 있을 때만)
create unique index if not exists uq_members_phone_digits
  on public.members ((regexp_replace(coalesce(phone, ''), '[^0-9]', '', 'g')))
  where nullif(regexp_replace(coalesce(phone, ''), '[^0-9]', '', 'g'), '') is not null;

-- 선행 스키마가 없는 환경에서도 실행되도록 최소 로열티 테이블 보장
create table if not exists public.member_points_ledger (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  order_id bigint,
  kind text not null, -- earn/use/adjust/reverse
  points integer not null,
  amount numeric(14,2) not null default 0,
  note text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_points_ledger_member_id on public.member_points_ledger(member_id);
create index if not exists idx_member_points_ledger_order_id on public.member_points_ledger(order_id);

-- 포인트 원장 멱등성: 동일 주문에서 같은 kind 1회만 반영
create unique index if not exists uq_member_points_ledger_member_order_kind
  on public.member_points_ledger(member_id, order_id, kind)
  where order_id is not null;

create table if not exists public.member_login_otps (
  id bigint generated by default as identity primary key,
  phone text not null,
  otp_hash text not null,
  expires_at timestamp without time zone not null,
  verified_at timestamp without time zone,
  tries integer not null default 0,
  status text not null default 'issued', -- issued/verified/expired/blocked
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_login_otps_phone_created_at
  on public.member_login_otps(phone, created_at desc);

create table if not exists public.member_sessions (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  session_token_hash text not null unique,
  device_label text,
  user_agent text,
  ip text,
  expires_at timestamp without time zone not null,
  revoked_at timestamp without time zone,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  last_seen_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_sessions_member_id on public.member_sessions(member_id);
create index if not exists idx_member_sessions_expires_at on public.member_sessions(expires_at);

create table if not exists public.member_notes (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  note text not null,
  tags text[] not null default '{}',
  created_by text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_notes_member_id on public.member_notes(member_id);

create table if not exists public.member_referral_events (
  id bigint generated by default as identity primary key,
  referrer_member_id bigint not null references public.members(id) on delete cascade,
  referred_member_id bigint not null references public.members(id) on delete cascade,
  referrer_points integer not null default 0,
  referred_points integer not null default 0,
  status text not null default 'approved', -- pending/approved/rejected
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  unique(referrer_member_id, referred_member_id)
);

create index if not exists idx_member_referral_events_referrer on public.member_referral_events(referrer_member_id);
create index if not exists idx_member_referral_events_referred on public.member_referral_events(referred_member_id);

create or replace function public.get_member_list_cursor(
  p_after_id bigint default null,
  p_limit integer default 100,
  p_q text default null
)
returns table (
  id bigint,
  member_no text,
  name text,
  full_name text,
  phone text,
  email text,
  birth_date text,
  gender text,
  nationality text,
  tier_code text,
  point_balance integer,
  lifetime_amount numeric,
  join_channel text,
  created_at timestamp without time zone
)
language sql
stable
as $$
  select
    m.id,
    m.member_no,
    m.name,
    m.full_name,
    m.phone,
    m.email,
    m.birth_date,
    m.gender,
    m.nationality,
    m.tier_code,
    m.point_balance,
    m.lifetime_amount,
    m.join_channel,
    m.created_at
  from public.members m
  where
    (p_after_id is null or m.id < p_after_id)
    and (
      coalesce(trim(p_q), '') = ''
      or m.name ilike ('%' || p_q || '%')
      or coalesce(m.full_name, '') ilike ('%' || p_q || '%')
      or coalesce(m.phone, '') ilike ('%' || p_q || '%')
      or coalesce(m.member_no, '') ilike ('%' || p_q || '%')
      or coalesce(m.email, '') ilike ('%' || p_q || '%')
    )
  order by m.id desc
  limit greatest(1, least(coalesce(p_limit, 100), 500));
$$;

create or replace function public.get_member_crm_summary(
  p_recent_days integer default 30,
  p_dormant_days integer default 90
)
returns table (
  total_members bigint,
  recent_active_members bigint,
  dormant_members bigint,
  total_lifetime_amount numeric,
  avg_order_amount numeric
)
language sql
stable
as $$
  with orders as (
    select
      o.member_id,
      o.total,
      o.created_at
    from public.pos_orders o
    where coalesce(o.member_id, 0) > 0
  ),
  recent_active as (
    select count(distinct member_id) as c
    from orders
    where created_at >= ((now() at time zone 'Asia/Bangkok') - make_interval(days => greatest(p_recent_days, 1)))
  ),
  dormant as (
    select count(*) as c
    from public.members m
    where not exists (
      select 1
      from orders o
      where o.member_id = m.id
        and o.created_at >= ((now() at time zone 'Asia/Bangkok') - make_interval(days => greatest(p_dormant_days, 1)))
    )
  )
  select
    (select count(*) from public.members) as total_members,
    coalesce((select c from recent_active), 0) as recent_active_members,
    coalesce((select c from dormant), 0) as dormant_members,
    coalesce((select sum(lifetime_amount) from public.members), 0) as total_lifetime_amount,
    coalesce((select avg(total) from orders), 0) as avg_order_amount;
$$;

create or replace function public.get_member_rfm_scores(
  p_limit integer default 5000
)
returns table (
  member_id bigint,
  recency_days integer,
  frequency_count integer,
  monetary_amount numeric,
  r_score integer,
  f_score integer,
  m_score integer,
  rfm_score text
)
language sql
stable
as $$
  with base as (
    select
      m.id as member_id,
      coalesce(
        floor(extract(epoch from ((now() at time zone 'Asia/Bangkok') - max(o.created_at))) / 86400)::int,
        9999
      ) as recency_days,
      coalesce(count(o.id), 0)::int as frequency_count,
      coalesce(sum(o.total), 0)::numeric as monetary_amount
    from public.members m
    left join public.pos_orders o
      on o.member_id = m.id
    group by m.id
  ),
  scored as (
    select
      b.*,
      ntile(5) over (order by b.recency_days asc) as r_score,
      ntile(5) over (order by b.frequency_count desc) as f_score,
      ntile(5) over (order by b.monetary_amount desc) as m_score
    from base b
  )
  select
    s.member_id,
    s.recency_days,
    s.frequency_count,
    s.monetary_amount,
    s.r_score,
    s.f_score,
    s.m_score,
    (s.r_score::text || s.f_score::text || s.m_score::text) as rfm_score
  from scored s
  order by s.r_score desc, s.f_score desc, s.m_score desc, s.member_id desc
  limit greatest(1, least(coalesce(p_limit, 5000), 20000));
$$;

