-- [사용 중단] 구성품(밥·치킨) 이미지를 미러(pos_menus.promo_id)에 복사하지 마세요.
-- 과거 이 스크립트로 채우면 POS 프로모 타일에 밥/단품 치킨 사진이 나옵니다.
--
-- 세트 전용 사진:
--   관리자 > POS 메뉴 > Delivery Ops 에서 [April] Set 1 등 미러 행에 업로드
--   (업로드 시 pos_menus.image + 배달 정책에 함께 저장됨)
--
-- 이미 잘못 복사된 URL 정리:
--   vercel-app/sql/pos_promo_mirror_image_fix_side_copy.sql
-- 진단:
--   vercel-app/sql/pos_promo_mirror_image_audit.sql
