-- @deprecated 이 파일만 실행하면 INSERT가 42501로 막힙니다.
-- 대신 pos_menu_ingredients_rls_policies.sql 을 실행하세요 (SELECT + INSERT/UPDATE/DELETE).
--
-- 이전 내용(참고):
-- DROP POLICY ... ; CREATE POLICY ... FOR SELECT USING (true);
