-- 상품 소개/랜딩 페이지용 카탈로그 테이블
-- 실행 위치: Supabase SQL Editor

create table if not exists public.product_catalog_items (
  id bigint generated by default as identity primary key,
  slug text null unique,
  title text not null,
  subtitle text null,
  summary text null,
  description text null,
  price_label text null,
  cover_image_url text null,
  gallery_urls jsonb not null default '[]'::jsonb,
  feature_bullets jsonb not null default '[]'::jsonb,
  cta_label text null,
  cta_url text null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_catalog_items_sort_idx
  on public.product_catalog_items (sort_order asc, updated_at desc);

create index if not exists product_catalog_items_active_idx
  on public.product_catalog_items (is_active, sort_order asc);

-- updated_at 자동 갱신 트리거
create or replace function public.touch_updated_at_product_catalog_items()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_updated_at_product_catalog_items on public.product_catalog_items;

create trigger trg_touch_updated_at_product_catalog_items
before update on public.product_catalog_items
for each row
execute function public.touch_updated_at_product_catalog_items();

