-- 매장 개선 과제(CAPA) — 발견 → 담당 → 기한 → 조치 → 재확인 → 완료
-- Storage: 버킷 store-action-photos — store_action_photos_storage_bucket.sql 또는 앱 presign 자동 생성
-- 실행: Supabase SQL Editor에 이 파일만 복사 → Run

CREATE TABLE IF NOT EXISTS store_action_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_name text NOT NULL,
  title text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT '기타',
  priority text NOT NULL DEFAULT '보통',
  status text NOT NULL DEFAULT 'open',
  owner_name text NOT NULL DEFAULT '',
  owner_user_id text,
  due_date date,
  verifier_name text NOT NULL DEFAULT '',
  verifier_user_id text,
  verified_at timestamptz,
  verification_note text NOT NULL DEFAULT '',
  action_plan text NOT NULL DEFAULT '',
  resolution_note text NOT NULL DEFAULT '',
  photo_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  after_photo_urls jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_type text NOT NULL DEFAULT 'manual',
  source_ref text NOT NULL DEFAULT '',
  linked_repair_ticket_id bigint,
  repeat_count integer NOT NULL DEFAULT 0,
  created_by text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_store_action_items_store_status
  ON store_action_items (store_name, status);

CREATE INDEX IF NOT EXISTS idx_store_action_items_due
  ON store_action_items (due_date);

CREATE INDEX IF NOT EXISTS idx_store_action_items_owner
  ON store_action_items (owner_name);

CREATE INDEX IF NOT EXISTS idx_store_action_items_status_due
  ON store_action_items (status, due_date);

CREATE INDEX IF NOT EXISTS idx_store_action_items_created
  ON store_action_items (created_at DESC);

COMMENT ON TABLE store_action_items IS '매장 개선 과제(CAPA) — 운영 표준·교육·청결 등 조치·재확인 추적';
COMMENT ON COLUMN store_action_items.status IS 'open | in_progress | pending_verify | completed | cancelled';
COMMENT ON COLUMN store_action_items.source_type IS 'manual | visit | check_fail | hq';
