-- ============================================================
-- Grab 메뉴 일괄 등록 (테스트용)
-- 사용법: Supabase 대시보드 > SQL Editor > 붙여넣기 > Run
-- vat_included=true, is_active=true, 재료 연결 없음
-- ============================================================

INSERT INTO pos_menus (code, name, category, price, vat_included, is_active, sort_order) VALUES
('MENU001', 'Tteokbokki', 'Tteokbokki Series', 219, true, true, 1),
('MENU002', 'Rosé Tteokbokki', 'Tteokbokki Series', 269, true, true, 2),
('MENU003', 'Cheese Tteokbokki', 'Tteokbokki Series', 259, true, true, 3),
('MENU004', 'Triple Chicken', 'Triple Chicken', 599, true, true, 4),
('MENU005', 'Supreme Chicken', 'SPECIALTIES SERIES', 269, true, true, 5),
('MENU006', 'CHEESE TORNADO', 'SPECIALTIES SERIES', 169, true, true, 6),
('MENU007', 'RED HOT CHICKEN', 'SPECIALTIES SERIES', 149, true, true, 7),
('MENU008', 'SOY SAUCE AND SPRING ONION CHICKEN', 'SPECIALTIES SERIES', 159, true, true, 8),
('MENU009', 'CURRYCANE', 'SPECIALTIES SERIES', 159, true, true, 9),
('MENU010', 'CURRY SNOW ONION', 'SNOW SERIES', 169, true, true, 10),
('MENU011', 'SNOW ONION', 'SNOW SERIES', 159, true, true, 11),
('MENU012', 'HOT SNOW ONION', 'SNOW SERIES', 169, true, true, 12),
('MENU013', 'CHURRO', 'SIDE MENU', 140, true, true, 13),
('MENU014', 'Mozzarella Cheese Ball', 'SIDE MENU', 135, true, true, 14),
('MENU015', 'Kejun Fries', 'SIDE MENU', 130, true, true, 15),
('MENU016', 'Supreme Cajun Fries', 'SIDE MENU', 170, true, true, 16),
('MENU017', 'ONION RINGS', 'SIDE MENU', 120, true, true, 17),
('MENU018', 'Choongman Kimchi 200 g.', 'SIDE DISH', 70, true, true, 18),
('MENU019', 'Choongman Kimchi 500 g.', 'SIDE DISH', 130, true, true, 19),
('MENU020', 'Pickled Radish 200 g.', 'SIDE DISH', 140, true, true, 20),
('MENU021', 'Pickled Radish 30 g.', 'SIDE DISH', 30, true, true, 21),
('MENU022', 'ข้าวญี่ปุ่น', 'SIDE DISH', 30, true, true, 22),
('MENU023', 'Cajun Chicken Salad', 'salad', 179, true, true, 23),
('MENU024', 'Caesar Salad', 'salad', 169, true, true, 24),
('MENU025', 'SOY SAUCE CHICKEN', 'ORIGINAL SERIES', 149, true, true, 25),
('MENU026', 'GOLDEN FRIED CHICKEN', 'ORIGINAL SERIES', 139, true, true, 26),
('MENU027', 'SWEET YANGNYEOM', 'ORIGINAL SERIES', 149, true, true, 27),
('MENU028', 'SPICY YANGNYEOM', 'ORIGINAL SERIES', 149, true, true, 28),
('MENU029', 'KIMCHI SOUP With Rice', 'KOREAN SOUP', 219, true, true, 29),
('MENU030', 'Samgyetang', 'KOREAN SOUP', 350, true, true, 30),
('MENU031', 'SOFT TOFU SOUP With Rice', 'KOREAN SOUP', 239, true, true, 31),
('MENU032', 'Seafood-Jjigae Soup with rice', 'KOREAN SOUP', 239, true, true, 32),
('MENU033', 'DAK GALBI CHEESE', 'KOREAN FOOD SERIES', 279, true, true, 33),
('MENU034', 'SPICY CHICKEN', 'KOREAN FOOD SERIES', 219, true, true, 34),
('MENU035', 'GOCHUJANG BULGOGI A La Cart', 'KOREAN FOOD SERIES', 240, true, true, 35),
('MENU036', 'KIMCHI FRIED RICE', 'KOREAN FOOD SERIES', 199, true, true, 36),
('MENU037', 'JJAJANG BOKUM', 'KOREAN FOOD SERIES', 219, true, true, 37),
('MENU038', 'Cheese Bulgogi Lava', 'KOREAN FOOD SERIES', 279, true, true, 38),
('MENU039', 'Cheese Cream Kimchi Rice', 'KOREAN FOOD SERIES', 269, true, true, 39),
('MENU040', 'SOY SAUCE BULGOGI A La Cart', 'KOREAN FOOD SERIES', 240, true, true, 40),
('MENU041', 'Jjampong', 'KOREAN FOOD SERIES', 289, true, true, 41),
('MENU042', 'KIMCHI   FRIED   UDON', 'KOREAN FOOD SERIES', 209, true, true, 42),
('MENU043', 'GOCHUJANG BULGOGI SET', 'KOREAN FOOD SERIES', 280, true, true, 43),
('MENU044', 'SOY SAUCE BULGOGI SET', 'KOREAN FOOD SERIES', 280, true, true, 44),
('MENU045', 'Chupa Chups Green Apple', 'DRINKS เครื่องดื่ม', 55, true, true, 45),
('MENU046', '7UP No Sugar Strawberry Lemon', 'DRINKS เครื่องดื่ม', 30, true, true, 46),
('MENU047', 'Mirinda Orange', 'DRINKS เครื่องดื่ม', 30, true, true, 47),
('MENU048', 'Mirinda Green Cream', 'DRINKS เครื่องดื่ม', 30, true, true, 48),
('MENU049', 'Aquafina', 'DRINKS เครื่องดื่ม', 20, true, true, 49),
('MENU050', 'Lipton Lemon Za', 'DRINKS เครื่องดื่ม', 30, true, true, 50),
('MENU051', '7UP No Sugar Pineapple Peach Soda', 'DRINKS เครื่องดื่ม', 30, true, true, 51),
('MENU052', 'Pepsi', 'DRINKS เครื่องดื่ม', 30, true, true, 52),
('MENU053', 'Chupa Chups Strawberry', 'DRINKS เครื่องดื่ม', 55, true, true, 53),
('MENU054', '7UP Lemon Soda', 'DRINKS เครื่องดื่ม', 30, true, true, 54),
('MENU055', 'Chupa Chups Melon & Cream', 'DRINKS เครื่องดื่ม', 55, true, true, 55),
('MENU056', 'Pepsi Zero Sugar', 'DRINKS เครื่องดื่ม', 30, true, true, 56),
('MENU057', 'PEAR IN YOU', 'DRINKS เครื่องดื่ม', 85, true, true, 57),
('MENU058', 'Chupa Chups Grape', 'DRINKS เครื่องดื่ม', 55, true, true, 58),
('MENU059', 'GRAPE FROM THE TREE', 'DRINKS เครื่องดื่ม', 85, true, true, 59),
('MENU060', 'Chupa Chups Cherry Bubble Gum', 'DRINKS เครื่องดื่ม', 55, true, true, 60),
('MENU061', 'SHIKYE', 'DRINKS เครื่องดื่ม', 85, true, true, 61),
('MENU062', 'Mirinda Strawberry', 'DRINKS เครื่องดื่ม', 30, true, true, 62),
('MENU063', 'Lipton Lemon Ice Tea', 'DRINKS เครื่องดื่ม', 30, true, true, 63),
('MENU064', 'Chupa Chups Watermelon', 'DRINKS เครื่องดื่ม', 55, true, true, 64),
('MENU065', 'Spicy Yangnyeom Chicken Dosirak', 'Dosirak', 119, true, true, 65),
('MENU066', 'Soy Sauce Chicken Dosirak', 'Dosirak', 119, true, true, 66),
('MENU067', 'Gochujang Bulgogi Dosirak', 'Dosirak', 159, true, true, 67),
('MENU068', 'Soy Sauce Bulgogi Dosirak', 'Dosirak', 159, true, true, 68),
('MENU069', 'Buldak Dosirak', 'Dosirak', 159, true, true, 69),
('MENU070', 'Snow Onion Chicken Dosirak', 'Dosirak', 129, true, true, 70),
('MENU071', 'GUCHUJANG Bar.B.Q FRIED CHICKEN', 'Bar.B.Q FRIED CHICKEN SERIES', 159, true, true, 71),
('MENU072', 'SOY SAUCE Bar.B.Q FRIED CHICKEN', 'Bar.B.Q FRIED CHICKEN SERIES', 159, true, true, 72),
('MENU073', 'GARLIC Bar.B.Q FRIED CHICKEN', 'Bar.B.Q FRIED CHICKEN SERIES', 159, true, true, 73),
('MENU074', 'CURRY Bar.B.Q FRIED CHICKEN', 'Bar.B.Q FRIED CHICKEN SERIES', 159, true, true, 74),
('MENU075', 'Banban Chicken', 'Banban', 259, true, true, 75)
ON CONFLICT (code) DO NOTHING;
