import type { SaasModuleKey } from "@/lib/saas-module-pricing"

/** admin 경로 → SaaS 모듈. null = 게이트 없음(대시보드·미과금 영역). */
export function resolveAdminPathSaasModule(pathname: string): SaasModuleKey | null {
  const p = normalizeAdminPath(pathname)
  if (!p || p === "/admin" || p === "/admin/settings" || p === "/admin/help") return null
  if (p.startsWith("/admin/ai-center")) return "ai_center"
  if (p.startsWith("/admin/notices")) return "notices"
  if (p.startsWith("/admin/company-documents")) return "documents"
  if (p.startsWith("/admin/work-log")) return "work_log"
  if (p.startsWith("/admin/pos-cost-analysis")) return "cost_analysis"
  if (p.startsWith("/admin/crm") || p.startsWith("/admin/members")) return "member_mgmt"
  if (p.startsWith("/admin/marketing")) return "marketing"
  if (
    p.startsWith("/admin/live-store-sales") ||
    p.startsWith("/admin/ops-center") ||
    p.startsWith("/admin/sales-management") ||
    p.startsWith("/admin/total-sales")
  ) {
    return "pos_base"
  }
  if (p.startsWith("/admin/interior")) return "logistics"
  if (
    p.startsWith("/admin/store-ops") ||
    p.startsWith("/admin/store-check") ||
    p.startsWith("/admin/store-visit") ||
    p.startsWith("/admin/store-repairs") ||
    p.startsWith("/admin/complaints")
  ) {
    return "pos_base"
  }
  if (p === "/pos" || p.startsWith("/pos/")) return "pos_base"
  if (p.startsWith("/admin/pos-")) return "pos_base"
  if (
    p.startsWith("/admin/attendance") ||
    p.startsWith("/admin/leave") ||
    p.startsWith("/admin/hr-calendar") ||
    p.startsWith("/admin/payroll") ||
    p.startsWith("/admin/employees") ||
    p.startsWith("/admin/hr-policies") ||
    p.startsWith("/admin/hr")
  ) {
    return "attendance"
  }
  if (
    p.startsWith("/admin/items") ||
    p.startsWith("/admin/vendors") ||
    p.startsWith("/admin/orders") ||
    p.startsWith("/admin/order-create") ||
    p.startsWith("/admin/stock") ||
    p.startsWith("/admin/inbound") ||
    p.startsWith("/admin/outbound") ||
    p.startsWith("/admin/accounting/purchase-order")
  ) {
    return "logistics"
  }
  if (
    p.startsWith("/admin/receivable-payable") ||
    p.startsWith("/admin/expense-management") ||
    p.startsWith("/admin/petty-cash") ||
    p.startsWith("/admin/bank-transactions") ||
    p.startsWith("/admin/depreciation") ||
    p.startsWith("/admin/financial-statements") ||
    p.startsWith("/admin/chart-of-accounts") ||
    p.startsWith("/admin/tax-filing") ||
    p.startsWith("/admin/accounting")
  ) {
    return "accounting"
  }
  return null
}

/** API 경로 prefix → 모듈 (긴 prefix 우선). null = 게이트 생략. */
export const API_PATH_RULES: ReadonlyArray<{ prefix: string; module: SaasModuleKey }> = [
  { prefix: "/api/ai/", module: "ai_center" },
  { prefix: "/api/crm/", module: "member_mgmt" },
  { prefix: "/api/members", module: "member_mgmt" },
  { prefix: "/api/member-", module: "member_mgmt" },
  { prefix: "/api/marketing", module: "marketing" },
  { prefix: "/api/sendNotice", module: "notices" },
  { prefix: "/api/getSentNotices", module: "notices" },
  { prefix: "/api/getNotice", module: "notices" },
  { prefix: "/api/noticeTemplates", module: "notices" },
  { prefix: "/api/deleteNoticeAdmin", module: "notices" },
  { prefix: "/api/updateNoticeAdmin", module: "notices" },
  { prefix: "/api/remindNoticeUnread", module: "notices" },
  { prefix: "/api/applyNoticeUnreadAllowanceExclusion", module: "notices" },
  { prefix: "/api/estimateNoticeRecipients", module: "notices" },
  { prefix: "/api/uploadNoticeAttachment", module: "notices" },
  { prefix: "/api/getCompanyHybridDocument", module: "documents" },
  { prefix: "/api/saveCompanyHybridDocument", module: "documents" },
  { prefix: "/api/deleteCompanyHybridDocument", module: "documents" },
  { prefix: "/api/recordCompanyHybridDocument", module: "documents" },
  { prefix: "/api/uploadCompanyHybridDocument", module: "documents" },
  { prefix: "/api/workLog", module: "work_log" },
  { prefix: "/api/getPosCostAnalysis", module: "cost_analysis" },
  { prefix: "/api/getPosMenuCostAnalysis", module: "cost_analysis" },
  { prefix: "/api/getMenuCost", module: "cost_analysis" },
  { prefix: "/api/costSettings", module: "cost_analysis" },
  { prefix: "/api/pos/kbank/", module: "kbank" },
  { prefix: "/api/pos/member-tier-rates", module: "member_mgmt" },
  { prefix: "/api/linkpos/", module: "kbank" },
  { prefix: "/api/grab", module: "grab" },
  { prefix: "/api/repairGrab", module: "grab" },
  { prefix: "/api/getGrab", module: "grab" },
  { prefix: "/api/savePosMenu", module: "pos_base" },
  { prefix: "/api/getPosMenu", module: "pos_base" },
  { prefix: "/api/importPosMenus", module: "pos_base" },
  { prefix: "/api/savePosOrder", module: "pos_base" },
  { prefix: "/api/getPosOrders", module: "pos_base" },
  { prefix: "/api/getPosOrder", module: "pos_base" },
  { prefix: "/api/updatePosOrder", module: "pos_base" },
  { prefix: "/api/posClose", module: "pos_base" },
  { prefix: "/api/getPosSettlement", module: "pos_base" },
  { prefix: "/api/savePosSettlement", module: "pos_base" },
  { prefix: "/api/getPosPrinter", module: "pos_base" },
  { prefix: "/api/savePosPrinter", module: "pos_base" },
  { prefix: "/api/getPosCoupons", module: "pos_base" },
  { prefix: "/api/savePosCoupon", module: "pos_base" },
  { prefix: "/api/posBusinessDay", module: "pos_base" },
  { prefix: "/api/posPrintJobs", module: "pos_base" },
  { prefix: "/api/posRealtime", module: "pos_base" },
  { prefix: "/api/posTaxInvoice", module: "pos_base" },
  { prefix: "/api/getLeave", module: "attendance" },
  { prefix: "/api/processLeave", module: "attendance" },
  { prefix: "/api/getAttendance", module: "attendance" },
  { prefix: "/api/processAttendance", module: "attendance" },
  { prefix: "/api/getPayroll", module: "attendance" },
  { prefix: "/api/savePayroll", module: "attendance" },
  { prefix: "/api/publishPayroll", module: "attendance" },
  { prefix: "/api/payroll", module: "attendance" },
  { prefix: "/api/getAdminEmployee", module: "attendance" },
  { prefix: "/api/saveAdminEmployee", module: "attendance" },
  { prefix: "/api/deleteAdminEmployee", module: "attendance" },
  { prefix: "/api/getHrPol", module: "attendance" },
  { prefix: "/api/saveHrPolicy", module: "attendance" },
  { prefix: "/api/confirmHrPolicy", module: "attendance" },
  { prefix: "/api/getMyHrPol", module: "attendance" },
  { prefix: "/api/employeeJobCatalog", module: "attendance" },
  { prefix: "/api/franchiseeMultiStore", module: "attendance" },
  { prefix: "/api/getEvaluation", module: "attendance" },
  { prefix: "/api/saveEvaluation", module: "attendance" },
  { prefix: "/api/warningLetter", module: "attendance" },
  { prefix: "/api/getStoreJobHeadcount", module: "attendance" },
  { prefix: "/api/saveStoreJobHeadcount", module: "attendance" },
  { prefix: "/api/getAdminItems", module: "logistics" },
  { prefix: "/api/saveItem", module: "logistics" },
  { prefix: "/api/deleteItem", module: "logistics" },
  { prefix: "/api/getVendors", module: "logistics" },
  { prefix: "/api/saveVendor", module: "logistics" },
  { prefix: "/api/getAdminOrders", module: "logistics" },
  { prefix: "/api/processOrder", module: "logistics" },
  { prefix: "/api/getStoreStock", module: "logistics" },
  { prefix: "/api/adjustStock", module: "logistics" },
  { prefix: "/api/getInbound", module: "logistics" },
  { prefix: "/api/savePurchaseOrder", module: "logistics" },
  { prefix: "/api/getIncomeStatement", module: "accounting" },
  { prefix: "/api/getBalanceSheet", module: "accounting" },
  { prefix: "/api/vatLedger", module: "accounting" },
  { prefix: "/api/pp36Ledger", module: "accounting" },
  { prefix: "/api/pnd54Ledger", module: "accounting" },
  { prefix: "/api/withholdingTax", module: "accounting" },
  { prefix: "/api/getReceivablePayable", module: "accounting" },
  { prefix: "/api/getBankTransaction", module: "accounting" },
  { prefix: "/api/addBankTransaction", module: "accounting" },
  { prefix: "/api/getBankAccountAuditLogs", module: "accounting" },
  { prefix: "/api/getBankWithdrawalsForCardBillQueueMark", module: "accounting" },
  { prefix: "/api/getBankWithdrawalsForPettyQueueMark", module: "accounting" },
  { prefix: "/api/getCardBillAllocation", module: "accounting" },
  { prefix: "/api/getLinkedReceivablesForBankTx", module: "accounting" },
  { prefix: "/api/getOpenReceivablesForBankTx", module: "accounting" },
  { prefix: "/api/linkReceivableFromBankTransaction", module: "accounting" },
  { prefix: "/api/unlinkReceivableFromBankTransaction", module: "accounting" },
  { prefix: "/api/linkPayableSettlement", module: "accounting" },
  { prefix: "/api/unlinkPayableSettlement", module: "accounting" },
  { prefix: "/api/markBankTransactionForCardBill", module: "accounting" },
  { prefix: "/api/markBankTransactionForPettyCash", module: "accounting" },
  { prefix: "/api/markOutboundInvoicesPrinted", module: "logistics" },
  { prefix: "/api/exportPp30RdPrepTxt", module: "accounting" },
  { prefix: "/api/getTaxInvoiceDepositSeq", module: "accounting" },
  { prefix: "/api/issueCompanyHybridDocumentWatermark", module: "documents" },
  { prefix: "/api/auditOfficePayrollManagers", module: "attendance" },
  { prefix: "/api/getOfficePayrollAccess", module: "attendance" },
  { prefix: "/api/getIngredientUsageVariance", module: "cost_analysis" },
  { prefix: "/api/pos-printer-settings", module: "pos_base" },
  { prefix: "/api/uploadExpenseAttachment", module: "accounting" },
  { prefix: "/api/uploadMarketingMaterialInstallPhoto", module: "marketing" },
  { prefix: "/api/uploadStoreCheckPhoto", module: "pos_base" },
  { prefix: "/api/registerCardExpenseFromBankTransaction", module: "accounting" },
  { prefix: "/api/registerPettyReplenishFromBankTransaction", module: "accounting" },
  { prefix: "/api/addReceivableStoreCredit", module: "accounting" },
  { prefix: "/api/getPettyCash", module: "accounting" },
  { prefix: "/api/getTrialBalance", module: "accounting" },
  { prefix: "/api/getAccounting", module: "accounting" },
  { prefix: "/api/saveAccounting", module: "accounting" },
  { prefix: "/api/getTaxReadiness", module: "accounting" },
  { prefix: "/api/getThaiTax", module: "accounting" },
  { prefix: "/api/getCorporateTax", module: "accounting" },
  { prefix: "/api/exportVat", module: "accounting" },
  { prefix: "/api/exportPnd", module: "accounting" },
  { prefix: "/api/exportKt20k", module: "accounting" },
  { prefix: "/api/exportCorporateTax", module: "accounting" },
  { prefix: "/api/exportAccounting", module: "accounting" },
  { prefix: "/api/incomeStatement", module: "accounting" },
  { prefix: "/api/postIncomeExpense", module: "accounting" },
  { prefix: "/api/getWorkLog", module: "work_log" },
  { prefix: "/api/saveWorkLog", module: "work_log" },
  { prefix: "/api/deleteWorkLog", module: "work_log" },
  { prefix: "/api/getOutbound", module: "logistics" },
  { prefix: "/api/saveOutbound", module: "logistics" },
  { prefix: "/api/deleteOutbound", module: "logistics" },
  { prefix: "/api/getFixedExpenses", module: "accounting" },
  { prefix: "/api/saveFixedAsset", module: "accounting" },
  { prefix: "/api/getExpense", module: "accounting" },
  { prefix: "/api/addExpense", module: "accounting" },
  { prefix: "/api/executeExpense", module: "accounting" },
  { prefix: "/api/executeWithdrawal", module: "accounting" },
  { prefix: "/api/extractExpenseDocument", module: "accounting" },
  { prefix: "/api/registerExpense", module: "accounting" },
  { prefix: "/api/registerPurchase", module: "accounting" },
  { prefix: "/api/getTillList", module: "accounting" },
  { prefix: "/api/addTillTransaction", module: "accounting" },
  { prefix: "/api/getEvaluation", module: "attendance" },
  { prefix: "/api/saveEvaluation", module: "attendance" },
  { prefix: "/api/summarizeEvaluation", module: "attendance" },
  { prefix: "/api/warningLetter", module: "attendance" },
  { prefix: "/api/uploadWarningLetter", module: "attendance" },
  { prefix: "/api/deleteWarningLetter", module: "attendance" },
  { prefix: "/api/getInterior", module: "logistics" },
  { prefix: "/api/saveInterior", module: "logistics" },
  { prefix: "/api/extractInteriorQuoteAmount", module: "logistics" },
  { prefix: "/api/getInteriorDashboardSummary", module: "logistics" },
  { prefix: "/api/getInteriorFiles", module: "logistics" },
  { prefix: "/api/getInteriorLayoutZoneBackground", module: "logistics" },
  { prefix: "/api/saveInteriorLayoutZoneBackground", module: "logistics" },
  { prefix: "/api/saveInteriorProjectFile", module: "logistics" },
  { prefix: "/api/payInteriorExpense", module: "logistics" },
  { prefix: "/api/getPosSales", module: "pos_base" },
  { prefix: "/api/posSalesByMenu", module: "pos_base" },
  { prefix: "/api/getLiveStoreSales", module: "pos_base" },
  { prefix: "/api/getSalesManagement", module: "pos_base" },
  { prefix: "/api/getTotalSales", module: "pos_base" },
  { prefix: "/api/sauces/", module: "logistics" },
  { prefix: "/api/saveCheckResult", module: "pos_base" },
  { prefix: "/api/getCheckResult", module: "pos_base" },
  { prefix: "/api/getStoreCheck", module: "pos_base" },
  { prefix: "/api/updateComplaintLog", module: "pos_base" },
  { prefix: "/api/getComplaint", module: "pos_base" },
  { prefix: "/api/getStoreRepair", module: "pos_base" },
  { prefix: "/api/saveStoreRepair", module: "pos_base" },
  { prefix: "/api/getStoreVisit", module: "pos_base" },
  { prefix: "/api/saveStoreVisit", module: "pos_base" },
  { prefix: "/api/validatePosCoupon", module: "pos_base" },
  { prefix: "/api/getPosPromo", module: "pos_base" },
  { prefix: "/api/savePosPromo", module: "pos_base" },
  { prefix: "/api/markPosOrder", module: "pos_base" },
  { prefix: "/api/correctPosOrder", module: "pos_base" },
  { prefix: "/api/finalizePosClose", module: "pos_base" },
  { prefix: "/api/validatePosClose", module: "pos_base" },
  { prefix: "/api/getPosChannel", module: "pos_base" },
  { prefix: "/api/importPosChannel", module: "pos_base" },
  { prefix: "/api/savePosChannel", module: "pos_base" },
  { prefix: "/api/getPosPayment", module: "pos_base" },
  { prefix: "/api/savePosPayment", module: "pos_base" },
  { prefix: "/api/getPosTable", module: "pos_base" },
  { prefix: "/api/savePosTable", module: "pos_base" },
  { prefix: "/api/getPosDevice", module: "pos_base" },
  { prefix: "/api/savePosDevice", module: "pos_base" },
  { prefix: "/api/registerPos", module: "pos_base" },
  { prefix: "/api/verifyPosDrawer", module: "pos_base" },
  { prefix: "/api/savePosDrawer", module: "pos_base" },
  { prefix: "/api/getPosBusinessDay", module: "pos_base" },
  { prefix: "/api/savePosBusinessDay", module: "pos_base" },
  { prefix: "/api/getPosDelivery", module: "pos_base" },
  { prefix: "/api/savePosDelivery", module: "pos_base" },
  { prefix: "/api/getGrab", module: "grab" },
  { prefix: "/api/saveGrab", module: "grab" },
  { prefix: "/api/markGrab", module: "grab" },
  { prefix: "/api/grab", module: "grab" },
  { prefix: "/api/getPos", module: "pos_base" },
  { prefix: "/api/savePos", module: "pos_base" },
  { prefix: "/api/deletePos", module: "pos_base" },
  { prefix: "/api/updatePos", module: "pos_base" },
  { prefix: "/api/importPos", module: "pos_base" },
  { prefix: "/api/clearPos", module: "pos_base" },
  { prefix: "/api/posSales", module: "pos_base" },
  { prefix: "/api/posDelivery", module: "pos_base" },
  { prefix: "/api/posKbank", module: "pos_base" },
  { prefix: "/api/posCard", module: "pos_base" },
  { prefix: "/api/posCash", module: "pos_base" },
  { prefix: "/api/claimKitchen", module: "pos_base" },
  { prefix: "/api/markKitchen", module: "pos_base" },
  { prefix: "/api/applyPosMenu", module: "pos_base" },
  { prefix: "/api/applyDuePrice", module: "pos_base" },
  { prefix: "/api/getMenuPermission", module: "pos_base" },
  { prefix: "/api/setMenuPermission", module: "pos_base" },
  { prefix: "/api/addChecklist", module: "pos_base" },
  { prefix: "/api/addStoreRepair", module: "pos_base" },
  { prefix: "/api/deleteMarketing", module: "marketing" },
  { prefix: "/api/importMarketing", module: "marketing" },
  { prefix: "/api/exportMarketing", module: "marketing" },
  { prefix: "/api/saveMarketing", module: "marketing" },
  { prefix: "/api/getMarketing", module: "marketing" },
  { prefix: "/api/lineOa/", module: "marketing" },
  { prefix: "/api/deleteInterior", module: "logistics" },
  { prefix: "/api/deleteInbound", module: "logistics" },
  { prefix: "/api/getPurchase", module: "logistics" },
  { prefix: "/api/processPurchase", module: "logistics" },
  { prefix: "/api/getWarehouse", module: "logistics" },
  { prefix: "/api/getItemV", module: "logistics" },
  { prefix: "/api/addPettyCash", module: "accounting" },
  { prefix: "/api/deletePettyCash", module: "accounting" },
  { prefix: "/api/addBank", module: "accounting" },
  { prefix: "/api/deleteBank", module: "accounting" },
  { prefix: "/api/addBalance", module: "accounting" },
  { prefix: "/api/deleteManualBalance", module: "accounting" },
  { prefix: "/api/addTill", module: "accounting" },
  { prefix: "/api/deleteTill", module: "accounting" },
  { prefix: "/api/deleteExpense", module: "accounting" },
  { prefix: "/api/approveExpense", module: "accounting" },
  { prefix: "/api/exportPp36", module: "accounting" },
  { prefix: "/api/exportEtax", module: "accounting" },
  { prefix: "/api/exportIncome", module: "accounting" },
  { prefix: "/api/accounting/", module: "accounting" },
  { prefix: "/api/checkAttendance", module: "attendance" },
  { prefix: "/api/registerAttendance", module: "attendance" },
  { prefix: "/api/createAttendance", module: "attendance" },
  { prefix: "/api/approveNoClock", module: "attendance" },
  { prefix: "/api/calculatePayroll", module: "attendance" },
  { prefix: "/api/addEvaluation", module: "attendance" },
  { prefix: "/api/deleteEvaluation", module: "attendance" },
  { prefix: "/api/member-tiers", module: "member_mgmt" },
  { prefix: "/api/saveCompanyHybridDocumentCategory", module: "documents" },
  { prefix: "/api/deleteCompanyHybridDocumentCategory", module: "documents" },
  { prefix: "/api/getCompanyHybridDocuments", module: "documents" },
  { prefix: "/api/getCompanyHybridDocumentCategories", module: "documents" },
  { prefix: "/api/getCompanyHybridDocumentEvents", module: "documents" },
  { prefix: "/api/getCompanyHybridDocumentsSummary", module: "documents" },
  { prefix: "/api/recordCompanyHybridDocumentView", module: "documents" },
  { prefix: "/api/uploadCompanyHybridDocument", module: "documents" },
  { prefix: "/api/registerPosMainDevice", module: "pos_device" },
  { prefix: "/api/registerPosDevice", module: "pos_device" },
  { prefix: "/api/clearPosMainDevice", module: "pos_device" },
  { prefix: "/api/revokePosDevice", module: "pos_device" },
  { prefix: "/api/setPosMainDevice", module: "pos_device" },
  { prefix: "/api/getPosDevices", module: "pos_device" },
  { prefix: "/api/updatePosDeviceDisplayLabel", module: "pos_device" },
  { prefix: "/api/savePosDeviceRoleLimits", module: "pos_device" },
  { prefix: "/api/registerAttendanceQrDevice", module: "pos_device" },
  { prefix: "/api/getAttendanceQrDevices", module: "pos_device" },
  { prefix: "/api/checkAttendanceQrDevice", module: "pos_device" },
  { prefix: "/api/getAttendanceQrDisplay", module: "pos_device" },
  { prefix: "/api/getItems", module: "logistics" },
  { prefix: "/api/getItem", module: "logistics" },
  { prefix: "/api/saveItem", module: "logistics" },
  { prefix: "/api/deleteItem", module: "logistics" },
  { prefix: "/api/getItemCategories", module: "logistics" },
  { prefix: "/api/saveItemCategory", module: "logistics" },
  { prefix: "/api/deleteVendor", module: "logistics" },
  { prefix: "/api/getStock", module: "logistics" },
  { prefix: "/api/getAdminOrders", module: "logistics" },
  { prefix: "/api/processOrder", module: "logistics" },
  { prefix: "/api/getCombinedOutbound", module: "logistics" },
  { prefix: "/api/getBankAccounts", module: "accounting" },
  { prefix: "/api/getBankMemo", module: "accounting" },
  { prefix: "/api/getAccountSubjects", module: "accounting" },
  { prefix: "/api/getDepreciation", module: "accounting" },
  { prefix: "/api/getFixedAssets", module: "accounting" },
  { prefix: "/api/saveFixedAsset", module: "accounting" },
  { prefix: "/api/getFixedExpenses", module: "accounting" },
  { prefix: "/api/getPoBilling", module: "logistics" },
  { prefix: "/api/generateEtax", module: "accounting" },
  { prefix: "/api/getIncomeStatement", module: "accounting" },
  { prefix: "/api/getBalanceSheet", module: "accounting" },
  { prefix: "/api/getTrialBalance", module: "accounting" },
  { prefix: "/api/getTaxReadiness", module: "accounting" },
  { prefix: "/api/getThaiTax", module: "accounting" },
  { prefix: "/api/getCorporateTax", module: "accounting" },
  { prefix: "/api/getReceivable", module: "accounting" },
  { prefix: "/api/getPayable", module: "accounting" },
  { prefix: "/api/getMyPayroll", module: "attendance" },
  { prefix: "/api/getMyAttendance", module: "attendance" },
  { prefix: "/api/getPublicHoliday", module: "attendance" },
  { prefix: "/api/getEmployeeLatest", module: "attendance" },
  { prefix: "/api/getHrCalendar", module: "attendance" },
  { prefix: "/api/getAdminDashboard", module: "pos_base" },
  { prefix: "/api/getManagementMargin", module: "cost_analysis" },
  { prefix: "/api/submitDailyClose", module: "pos_base" },
  { prefix: "/api/posMenuCategories", module: "pos_base" },
  { prefix: "/api/replacePosMenu", module: "pos_base" },
  { prefix: "/api/getNoticeSenders", module: "notices" },
  { prefix: "/api/confirmNoticeRead", module: "notices" },
  { prefix: "/api/getCheckHistory", module: "pos_base" },
  { prefix: "/api/deleteCheck", module: "pos_base" },
  { prefix: "/api/getComplaintLogs", module: "pos_base" },
  { prefix: "/api/getStoreRepairs", module: "pos_base" },
  { prefix: "/api/getMyNotices", module: "notices" },
  { prefix: "/api/getMyLeave", module: "attendance" },
  { prefix: "/api/getMyOrder", module: "logistics" },
  { prefix: "/api/getMyUsage", module: "member_mgmt" },
  { prefix: "/api/getCardAccount", module: "accounting" },
  { prefix: "/api/getCardTransaction", module: "accounting" },
  { prefix: "/api/deleteCard", module: "accounting" },
  { prefix: "/api/getChecklist", module: "pos_base" },
  { prefix: "/api/getStoreGps", module: "attendance" },
  { prefix: "/api/getPriceSchedule", module: "pos_base" },
  { prefix: "/api/getPriceHistory", module: "pos_base" },
  { prefix: "/api/cancelPriceSchedule", module: "pos_base" },
  { prefix: "/api/getNextPos", module: "pos_base" },
  { prefix: "/api/getOrderFilter", module: "logistics" },
  { prefix: "/api/getOrderReceive", module: "logistics" },
  { prefix: "/api/getInvoice", module: "accounting" },
  { prefix: "/api/getKt20k", module: "accounting" },
  { prefix: "/api/getPnd91", module: "accounting" },
  { prefix: "/api/getSso", module: "accounting" },
  { prefix: "/api/getSubledger", module: "accounting" },
  { prefix: "/api/getAdjustment", module: "accounting" },
  { prefix: "/api/getApprovedExpense", module: "accounting" },
  { prefix: "/api/getEmployeeInput", module: "attendance" },
  { prefix: "/api/getEmployeeSalary", module: "attendance" },
  { prefix: "/api/getHqStock", module: "logistics" },
  { prefix: "/api/getHqWarehouse", module: "logistics" },
  { prefix: "/api/getIncomeExpense", module: "accounting" },
  { prefix: "/api/forceOutbound", module: "logistics" },
  { prefix: "/api/exportWithholding", module: "accounting" },
  { prefix: "/api/deleteAccountSubject", module: "accounting" },
  { prefix: "/api/deleteFixedExpense", module: "accounting" },
  { prefix: "/api/deletePurchaseAccrual", module: "accounting" },
  { prefix: "/api/deleteWarehouse", module: "logistics" },
  { prefix: "/api/saveAccount", module: "accounting" },
  { prefix: "/api/saveBank", module: "accounting" },
  { prefix: "/api/saveCard", module: "accounting" },
  { prefix: "/api/saveComplaint", module: "pos_base" },
  { prefix: "/api/saveCorporateTax", module: "accounting" },
  { prefix: "/api/saveFixed", module: "accounting" },
  { prefix: "/api/saveWarehouse", module: "logistics" },
  { prefix: "/api/importEmployees", module: "attendance" },
  { prefix: "/api/importItems", module: "logistics" },
  { prefix: "/api/importVendors", module: "logistics" },
  { prefix: "/api/getToday", module: "attendance" },
  { prefix: "/api/getWeekly", module: "attendance" },
  { prefix: "/api/getWarningLetter", module: "attendance" },
  { prefix: "/api/requestLeave", module: "attendance" },
  { prefix: "/api/processPos", module: "pos_base" },
  { prefix: "/api/processUsage", module: "member_mgmt" },
  { prefix: "/api/registerInbound", module: "logistics" },
  { prefix: "/api/repairForce", module: "logistics" },
  { prefix: "/api/runDepreciation", module: "accounting" },
  { prefix: "/api/patchStock", module: "logistics" },
  { prefix: "/api/posCancel", module: "pos_base" },
  { prefix: "/api/posDineIn", module: "pos_base" },
  { prefix: "/api/posPromo", module: "pos_base" },
  { prefix: "/api/migratePos", module: "pos_base" },
  { prefix: "/api/getUnlinkedBank", module: "accounting" },
  { prefix: "/api/getVatLedger", module: "accounting" },
  { prefix: "/api/restoreFromPrice", module: "pos_base" },
  { prefix: "/api/notificationSettings", module: "notices" },
  { prefix: "/api/saveNotification", module: "notices" },
  { prefix: "/api/getNotification", module: "notices" },
  { prefix: "/api/submitAttendance", module: "attendance" },
  { prefix: "/api/saveAttendance", module: "attendance" },
  { prefix: "/api/saveSchedule", module: "attendance" },
  { prefix: "/api/savePublicHoliday", module: "attendance" },
  { prefix: "/api/saveWarningLetter", module: "attendance" },
  { prefix: "/api/uploadWarningLetter", module: "attendance" },
  { prefix: "/api/deleteWarningLetter", module: "attendance" },
  { prefix: "/api/saveCheckResult", module: "pos_base" },
  { prefix: "/api/saveStoreRepair", module: "pos_base" },
  { prefix: "/api/saveStoreVisit", module: "pos_base" },
  { prefix: "/api/saveMarketing", module: "marketing" },
  { prefix: "/api/getMarketing", module: "marketing" },
  { prefix: "/api/saveInterior", module: "logistics" },
  { prefix: "/api/getInterior", module: "logistics" },
  { prefix: "/api/getAi", module: "ai_center" },
  { prefix: "/api/saveAi", module: "ai_center" },
  { prefix: "/api/saveMember", module: "member_mgmt" },
  { prefix: "/api/getMember", module: "member_mgmt" },
  { prefix: "/api/saveCoupon", module: "member_mgmt" },
  { prefix: "/api/getCoupon", module: "member_mgmt" },
  { prefix: "/api/saveCampaign", module: "marketing" },
  { prefix: "/api/getCampaign", module: "marketing" },
  { prefix: "/api/saveAd", module: "marketing" },
  { prefix: "/api/getAd", module: "marketing" },
  { prefix: "/api/saveInfluencer", module: "marketing" },
  { prefix: "/api/getInfluencer", module: "marketing" },
  { prefix: "/api/savePromo", module: "marketing" },
  { prefix: "/api/getPromo", module: "marketing" },
  { prefix: "/api/saveMaterial", module: "marketing" },
  { prefix: "/api/getMaterial", module: "marketing" },
  { prefix: "/api/sauces", module: "logistics" },
  { prefix: "/api/saveSauce", module: "logistics" },
  { prefix: "/api/getSauce", module: "logistics" },
  { prefix: "/api/saveHeadOffice", module: "logistics" },
  { prefix: "/api/saveIncomeExpense", module: "accounting" },
  { prefix: "/api/saveKt20k", module: "accounting" },
  { prefix: "/api/savePoBilling", module: "logistics" },
  { prefix: "/api/savePriceSchedule", module: "pos_base" },
  { prefix: "/api/saveSafetyStock", module: "logistics" },
  { prefix: "/api/sendPayroll", module: "attendance" },
  { prefix: "/api/setAccounting", module: "accounting" },
  { prefix: "/api/setupPayroll", module: "attendance" },
  { prefix: "/api/setupPublic", module: "attendance" },
  { prefix: "/api/storeTaxFiling", module: "accounting" },
  { prefix: "/api/submitStoreVisit", module: "pos_base" },
  { prefix: "/api/syncAllOrder", module: "accounting" },
  { prefix: "/api/syncExpense", module: "accounting" },
  { prefix: "/api/syncOrderReceivable", module: "accounting" },
  { prefix: "/api/getStorePurchaseJournal", module: "accounting" },
  { prefix: "/api/deleteStorePurchaseJournal", module: "accounting" },
  { prefix: "/api/syncPayroll", module: "attendance" },
  { prefix: "/api/syncPosMenu", module: "pos_base" },
  { prefix: "/api/updateBank", module: "accounting" },
  { prefix: "/api/updateChecklist", module: "pos_base" },
  { prefix: "/api/updateEvaluation", module: "attendance" },
  { prefix: "/api/updateExpense", module: "accounting" },
  { prefix: "/api/updateForceOutbound", module: "logistics" },
  { prefix: "/api/updateInbound", module: "logistics" },
  { prefix: "/api/updateInvoice", module: "accounting" },
  { prefix: "/api/updateItemOrder", module: "logistics" },
  { prefix: "/api/updateManagerCheck", module: "pos_base" },
  { prefix: "/api/updateManualBalance", module: "accounting" },
  { prefix: "/api/updateOrder", module: "logistics" },
  { prefix: "/api/updatePettyCash", module: "accounting" },
  { prefix: "/api/updatePurchaseOrder", module: "logistics" },
  { prefix: "/api/updateReceivable", module: "accounting" },
  { prefix: "/api/updateStoreRepair", module: "pos_base" },
  { prefix: "/api/updateWorkLog", module: "work_log" },
  { prefix: "/api/uploadCustomerDisplay", module: "pos_base" },
  { prefix: "/api/uploadEtax", module: "accounting" },
  { prefix: "/api/uploadInterior", module: "logistics" },
  { prefix: "/api/uploadLeave", module: "attendance" },
  { prefix: "/api/uploadMemberPortal", module: "member_mgmt" },
  { prefix: "/api/uploadPoQuotation", module: "logistics" },
  { prefix: "/api/uploadPosMenu", module: "pos_base" },
  { prefix: "/api/uploadSso", module: "accounting" },
  { prefix: "/api/uploadStoreRepair", module: "pos_base" },
  { prefix: "/api/validatePnd", module: "accounting" },
  { prefix: "/api/member", module: "member_mgmt" },
] as const

/** SaaS 게이트 검사 제외 API (로그인·공통·SaaS 관리·웹훅 등) */
export const SAAS_API_GATE_EXEMPT_PREFIXES = [
  "/api/loginCheck",
  "/api/getLoginData",
  "/api/getAppData",
  "/api/saas/",
  "/api/saasAdmin",
  "/api/getSaas",
  "/api/saveSaas",
  "/api/ai/module-status",
  "/api/member-portal/",
  "/api/posMenuImageProxy",
  "/api/imageProxy",
  "/api/translate",
  "/api/adminHelp",
  "/api/uploadComplaintPhoto",
  "/api/getStoreOpsAlertSummary",
  "/api/getInteriorDashboardSummary",
  "/api/ops/",
  "/api/oaplus/",
  "/api/getStoreList",
  "/api/getHeadOfficeInfo",
  "/api/getAdminDataLimits",
  "/api/getAdminRecentActivity",
  "/api/checkUserVisitStatus",
  "/api/changePassword",
  "/api/cron/",
  "/api/debug",
  "/api/webhooks/",
  "/api/checkPushToken",
  "/api/savePushToken",
  "/api/deletePushToken",
  "/api/adminHelpHandover",
  "/api/backfill",
  "/api/cleanup",
  "/api/health",
  "/api/logout",
  "/api/online-probe",
  "/api/notificationSettings",
  "/api/getSaasTenantSettings",
  "/api/saasAdminScope",
  "/api/saasBootstrap",
  "/api/line/webhook",
  "/api/lineOa/",
  "/api/adminHelpHandover",
] as const

export function resolveApiPathSaasModule(pathname: string): SaasModuleKey | null {
  const p = pathname.split("?")[0] || ""
  for (const ex of SAAS_API_GATE_EXEMPT_PREFIXES) {
    if (p === ex || p.startsWith(ex)) return null
  }
  const sorted = [...API_PATH_RULES].sort((a, b) => b.prefix.length - a.prefix.length)
  for (const rule of sorted) {
    if (p.startsWith(rule.prefix)) return rule.module
  }
  return null
}

export function isSaasGatedAdminHref(href: string): boolean {
  return resolveAdminPathSaasModule(href) != null
}

function normalizeAdminPath(pathname: string): string {
  const raw = String(pathname || "").trim()
  if (!raw) return ""
  const base = raw.split("?")[0] || ""
  if (base.length > 1 && base.endsWith("/")) return base.slice(0, -1)
  return base
}
