-- LINE CRM 데이터(고객/포인트/쿠폰 리포트) 적재용 확장 스키마
-- 실행 대상: Supabase SQL Editor (PostgreSQL)

alter table public.members
  add column if not exists full_name text,
  add column if not exists birth_date date,
  add column if not exists gender text,
  add column if not exists line_display_name text,
  add column if not exists line_member_type text,
  add column if not exists line_first_name text,
  add column if not exists line_last_name text,
  add column if not exists line_address text,
  add column if not exists line_subdistrict text,
  add column if not exists line_district text,
  add column if not exists line_province text,
  add column if not exists line_postcode text,
  add column if not exists line_membership_tier text,
  add column if not exists line_member_tag text,
  add column if not exists line_member_branch text,
  add column if not exists line_current_points integer,
  add column if not exists line_total_points integer,
  add column if not exists line_tier_points integer,
  add column if not exists line_usage_count integer,
  add column if not exists line_last_active_at timestamp without time zone,
  add column if not exists line_last_active_days integer,
  add column if not exists line_member_status text,
  add column if not exists line_registered_at timestamp without time zone,
  add column if not exists line_exported_at timestamp without time zone,
  add column if not exists consent_marketing boolean,
  add column if not exists consent_privacy boolean,
  add column if not exists consent_at timestamp without time zone,
  add column if not exists line_oa_friend boolean,
  add column if not exists line_oa_friend_at timestamp without time zone;

create table if not exists public.line_import_jobs (
  id text primary key,
  report_type text not null, -- customer / point / coupon
  file_name text not null,
  row_count integer not null default 0,
  success_count integer not null default 0,
  failed_count integer not null default 0,
  created_by text,
  exported_at timestamp without time zone,
  shop_name text,
  menu_name text,
  period_start date,
  period_end date,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create table if not exists public.line_import_rows (
  id bigint generated by default as identity primary key,
  job_id text not null references public.line_import_jobs(id) on delete cascade,
  row_no integer not null,
  report_type text not null,
  line_display_name text,
  phone text,
  full_name text,
  transaction_id text,
  coupon_code text,
  points integer,
  status text not null, -- success / failed / skipped
  message text,
  raw_payload jsonb,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_line_import_rows_job_id on public.line_import_rows(job_id);
create index if not exists idx_line_import_rows_phone on public.line_import_rows(phone);
