-- LINE/ERP/POS 공용 회원 도메인 스키마
-- 실행 대상: Supabase SQL Editor (PostgreSQL)

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  member_no text unique,
  name text not null,
  phone text,
  email text,
  source text not null default 'manual',
  status text not null default 'active',
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_members_name on public.members (name);
create index if not exists idx_members_phone on public.members (phone);

create table if not exists public.member_identities (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  provider text not null,
  provider_user_id text not null,
  display_name text,
  picture_url text,
  status text not null default 'active',
  linked_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  last_seen_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  unique(provider, provider_user_id)
);

create index if not exists idx_member_identities_member_id on public.member_identities (member_id);

create table if not exists public.member_events (
  id bigint generated by default as identity primary key,
  member_id bigint references public.members(id) on delete set null,
  event_id text not null unique,
  provider text not null,
  event_type text not null,
  status text not null default 'processed',
  payload jsonb,
  error_message text,
  processed_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_events_member_id on public.member_events (member_id);
create index if not exists idx_member_events_provider_event_type on public.member_events (provider, event_type);

create or replace function public.set_members_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now() at time zone 'Asia/Bangkok';
  return new;
end;
$$;

drop trigger if exists trg_members_set_updated_at on public.members;
create trigger trg_members_set_updated_at
before update on public.members
for each row
execute function public.set_members_updated_at();
