-- 회원 로열티(포인트/등급/쿠폰이슈) + POS 주문 회원키 확장
-- 실행 대상: Supabase SQL Editor (PostgreSQL)

alter table public.members
  add column if not exists tier_code text default 'BRONZE',
  add column if not exists lifetime_amount numeric(14,2) not null default 0,
  add column if not exists point_balance integer not null default 0;

create table if not exists public.member_tiers (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  min_amount numeric(14,2) not null default 0,
  point_rate numeric(8,4) not null default 0.0100,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create table if not exists public.member_tier_histories (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  prev_tier_code text,
  next_tier_code text not null,
  reason text,
  changed_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_tier_histories_member_id on public.member_tier_histories(member_id);

create table if not exists public.member_points_ledger (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  order_id bigint,
  kind text not null, -- earn/use/adjust/reverse
  points integer not null,
  amount numeric(14,2) not null default 0,
  note text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create index if not exists idx_member_points_ledger_member_id on public.member_points_ledger(member_id);
create index if not exists idx_member_points_ledger_order_id on public.member_points_ledger(order_id);

create table if not exists public.member_coupon_issues (
  id bigint generated by default as identity primary key,
  member_id bigint references public.members(id) on delete cascade,
  coupon_code text not null,
  issued_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  used_at timestamp without time zone,
  order_id bigint,
  status text not null default 'issued' -- issued/used/expired/cancelled
);

create index if not exists idx_member_coupon_issues_member_id on public.member_coupon_issues(member_id);
create index if not exists idx_member_coupon_issues_coupon_code on public.member_coupon_issues(coupon_code);

alter table public.pos_orders
  add column if not exists member_id bigint,
  add column if not exists member_no text,
  add column if not exists coupon_code text,
  add column if not exists coupon_discount_amt numeric(14,2) not null default 0,
  add column if not exists point_used integer not null default 0,
  add column if not exists point_earned integer not null default 0;

create index if not exists idx_pos_orders_member_id on public.pos_orders(member_id);

insert into public.member_tiers (code, name, min_amount, point_rate)
values
  ('BRONZE', 'Bronze', 0, 0.0100),
  ('SILVER', 'Silver', 10000, 0.0125),
  ('GOLD', 'Gold', 30000, 0.0150),
  ('VIP', 'VIP', 70000, 0.0200)
on conflict (code) do update
set
  name = excluded.name,
  min_amount = excluded.min_amount,
  point_rate = excluded.point_rate,
  updated_at = (now() at time zone 'Asia/Bangkok');
