-- POS 결제 수단 항목 (카드수기입력 항목관리)
-- 관리자 > POS 화면 구성 > 결제 기능에서 추가/수정/숨김
-- store_code null = 전역(모든 매장 공통)
create table if not exists public.pos_payment_method_items (
  id bigint generated by default as identity primary key,
  store_code text,
  category text not null default 'other' check (category in ('card', 'qr', 'delivery', 'other')),
  name text not null,
  hidden boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_pos_payment_method_items_store on public.pos_payment_method_items(store_code);
create index if not exists idx_pos_payment_method_items_category on public.pos_payment_method_items(category);

-- 시드: 기본 항목 (글로벌) - 테이블 비어있을 때만
insert into public.pos_payment_method_items (store_code, category, name, hidden, sort_order)
select * from (values
  (null::text, 'card', 'Visa', false, 1),
  (null, 'card', 'Master', false, 2),
  (null, 'card', 'Amex', false, 3),
  (null, 'card', 'JCB', false, 4),
  (null, 'card', 'Other', false, 99),
  (null, 'qr', 'TrueMoney', false, 1),
  (null, 'qr', 'WeChat', false, 2),
  (null, 'qr', 'Alipay', false, 3),
  (null, 'qr', 'UnionPay', false, 4),
  (null, 'qr', 'PromptPay', false, 5),
  (null, 'qr', 'LINE Pay', false, 6),
  (null, 'qr', 'Shopee Pay', false, 7),
  (null, 'qr', 'Other', false, 99),
  (null, 'delivery', 'Grab', false, 1),
  (null, 'delivery', 'Line Man', false, 2),
  (null, 'delivery', 'Shopee', false, 3),
  (null, 'delivery', 'Other', false, 99),
  (null, 'other', 'Gift Voucher', false, 1),
  (null, 'other', 'Online Banking', false, 2),
  (null, 'other', 'Other', false, 99)
) v(store_code, category, name, hidden, sort_order)
where not exists (select 1 from public.pos_payment_method_items limit 1);
