-- POS 배달앱 설정 테이블
-- 실행 대상: Supabase SQL Editor (PostgreSQL)
-- 관리자 화면 "배달앱 관리" 탭에서 설정 저장

create table if not exists public.pos_delivery_apps (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  match_keywords text[] not null default '{}',
  display_order integer not null default 0,
  enabled boolean not null default true,
  dine_out_enabled boolean not null default true,
  accent_color text,
  store_code text,
  created_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok'),
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);

create unique index if not exists idx_pos_delivery_apps_code_store on public.pos_delivery_apps (code, coalesce(store_code, ''));
create index if not exists idx_pos_delivery_apps_store_code on public.pos_delivery_apps(store_code);
create index if not exists idx_pos_delivery_apps_enabled on public.pos_delivery_apps(enabled) where enabled = true;

-- 시드: Grab, Line Man, Shopee, Other (store_code null = 전역) - 테이블 비어있을 때만
insert into public.pos_delivery_apps (code, name, match_keywords, display_order, enabled, dine_out_enabled, accent_color, store_code)
select 'grab', 'Grab', array['grab', '그랩', 'grab food'], 1, true, true, 'lime', null
where not exists (select 1 from public.pos_delivery_apps limit 1)
union all select 'lineman', 'Line Man', array['lineman', 'line man', '라인맨', 'lineman wongnai'], 2, true, true, 'sky', null
where not exists (select 1 from public.pos_delivery_apps limit 1)
union all select 'shopee', 'Shopee', array['shopee', '쇼피', 'shopee food'], 3, true, true, 'amber', null
where not exists (select 1 from public.pos_delivery_apps limit 1)
union all select 'other', 'Other', array['other', '기타'], 99, true, true, 'slate', null
where not exists (select 1 from public.pos_delivery_apps limit 1);

-- POS 결제 수단 설정 (카드/QR breakdown 키) - store_code당 1행
create table if not exists public.pos_payment_settings (
  store_code text primary key,
  card_keys text[] not null default array['Visa', 'Master', 'Amex', 'JCB', 'Other'],
  qr_keys text[] not null default array['TrueMoney', 'WeChat', 'Alipay', 'PromptPay', 'LINE Pay', 'Shopee Pay', 'Other'],
  updated_at timestamp without time zone not null default (now() at time zone 'Asia/Bangkok')
);
